#ifndef _ZCFG_RDM_OID_H
#define _ZCFG_RDM_OID_H

#define RDM_OID_DEVICE                           0 	/*Device*/
#define RDM_OID_SERVICE                          108	/*Device.Services*/
#define RDM_OID_PACKAGE                          144	/*Device.Services.X_ZYXEL_Package.i*/
#define RDM_OID_PACKAGE_INSTALL                  372	/*Device.Services.X_ZYXEL_Package_Install*/
#define RDM_OID_VOICE_SRV                        456	/*Device.Services.VoiceService.i*/
#define RDM_OID_VOICE_CAPB                       540	/*Device.Services.VoiceService.i.Capabilities*/
#define RDM_OID_VOICE_CAPB_SIP                   1344	/*Device.Services.VoiceService.i.Capabilities.SIP*/
#define RDM_OID_VOICE_CAPB_MGCP                  1644	/*Device.Services.VoiceService.i.Capabilities.MGCP*/
#define RDM_OID_VOICE_CAPB_H323                  1704	/*Device.Services.VoiceService.i.Capabilities.H323*/
#define RDM_OID_VOICE_CAPB_CODEC                 1788	/*Device.Services.VoiceService.i.Capabilities.Codec.i*/
#define RDM_OID_VOICE_PROF                       1968	/*Device.Services.VoiceService.i.VoiceProfile.i*/
#define RDM_OID_VOICE_PROF_SRV_PRO_INFO          2940	/*Device.Services.VoiceService.i.VoiceProfile.i.ServiceProviderInfo*/
#define RDM_OID_VOICE_PROF_SIP                   3072	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP*/
#define RDM_OID_VOICE_PROF_SIP_SUBSCRIBE_OBJ     4596	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP.EventSubscribe.i*/
#define RDM_OID_VOICE_PROF_SIP_RESP_MAP_OBJ      4752	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP.ResponseMap.i*/
#define RDM_OID_VOICE_PROF_RTP                   4860	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP*/
#define RDM_OID_VOICE_PROF_RTP_RTCP              5040	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.RTCP*/
#define RDM_OID_VOICE_PROF_RTP_SRTP              5148	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.SRTP*/
#define RDM_OID_VOICE_PROF_RTP_REDUNDANCY        5280	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.Redundancy*/
#define RDM_OID_VOICE_PROF_NUM_PLAN              5508	/*Device.Services.VoiceService.i.VoiceProfile.i.NumberingPlan*/
#define RDM_OID_VOICE_PROF_NUM_PLAN_PREFIX_INFO  5760	/*Device.Services.VoiceService.i.VoiceProfile.i.NumberingPlan.PrefixInfo.i*/
#define RDM_OID_VOICE_PROF_TONE                  5988	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone*/
#define RDM_OID_VOICE_PROF_TONE_EVENT            6096	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Event.i*/
#define RDM_OID_VOICE_PROF_TONE_DESCRIPTION      6180	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Description.i*/
#define RDM_OID_VOICE_PROF_TONE_PATTERN          6384	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Pattern.i*/
#define RDM_OID_VOICE_PROF_FAX_T38               6756	/*Device.Services.VoiceService.i.VoiceProfile.i.FaxT38*/
#define RDM_OID_VOICE_LINE                       6936	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i*/
#define RDM_OID_VOICE_LINE_SIP                   7308	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.SIP*/
#define RDM_OID_VOICE_LINE_SIP_EVENT_SUBS        7584	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.SIP.EventSubscribe.i*/
#define RDM_OID_VOICE_LINE_RINGER                7692	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer*/
#define RDM_OID_VOICE_LINE_RINGER_EVENT          7800	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Event.i*/
#define RDM_OID_VOICE_LINE_RINGER_DESCRIPTION    7884	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Description.i*/
#define RDM_OID_VOICE_LINE_RINGER_PATTERN        8040	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Pattern.i*/
#define RDM_OID_VOICE_LINE_CALLING_FEATURE       8172	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.CallingFeatures*/
#define RDM_OID_VOICE_LINE_PROCESSING            9672	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.VoiceProcessing*/
#define RDM_OID_VOICE_LINE_CODEC                 9828	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Codec*/
#define RDM_OID_VOICE_LINE_CODEC_LIST            10032	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Codec.List.i*/
#define RDM_OID_VOICE_LINE_SESSION               10284	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Session.i*/
#define RDM_OID_VOICE_LINE_STATS                 10440	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Stats*/
#define RDM_OID_VOICE_PHY_INTF                   11220	/*Device.Services.VoiceService.i.PhyInterface.i*/
#define RDM_OID_VOICE_PSTN                       11832	/*Device.Services.VoiceService.i.X_ZYXEL_PSTN.i*/
#define RDM_OID_VOICE_COMMON                     12012	/*Device.Services.VoiceService.i.X_ZYXEL_Common*/
#define RDM_OID_VOICE_PHONE_BOOK                 12384	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook*/
#define RDM_OID_SPEED_DIAL_BOOK                  12420	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.SpeedDialBook*/
#define RDM_OID_SPEED_DIAL_BOOK_LIST             12480	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.SpeedDialBook.List.i*/
#define RDM_OID_CALL_POLICY_BOOK                 12660	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.CallPolicyBook*/
#define RDM_OID_CALL_POLICY_BOOK_LIST            12744	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.CallPolicyBook.List.i*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK 12924	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK_IF_LIST 12984	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook.InterfaceList.i*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK_PORT_LIST 13068	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook.InterfaceList.i.PortList.i*/
#define RDM_OID_VOICE_FXO                        13128	/*Device.Services.VoiceService.i.X_ZYXEL_FXO*/
#define RDM_OID_VOICE_FXO_PORT                   13188	/*Device.Services.VoiceService.i.X_ZYXEL_FXO.Port.i*/
#define RDM_OID_VOICE_DECT                       13464	/*Device.Services.VoiceService.i.X_ZYXEL_DECT*/
#define RDM_OID_VOICE_DECT_B_S                   13524	/*Device.Services.VoiceService.i.X_ZYXEL_DECT.BaseStation*/
#define RDM_OID_VOICE_DECT_H_S                   14016	/*Device.Services.VoiceService.i.X_ZYXEL_DECT.Handset.i*/
#define RDM_OID_VOICE_CALL_STATUS                14340	/*Device.Services.VoiceService.i.X_ZYXEL_CALL_STATUS*/
#define RDM_OID_DEV_INFO                         14568	/*Device.DeviceInfo*/
#define RDM_OID_DEV_INFO_VEND_CONF_FILE          15108	/*Device.DeviceInfo.VendorConfigFile.i*/
#define RDM_OID_DEV_INFO_SUP_DATA_MODEL          15264	/*Device.DeviceInfo.SupportedDataModel.i*/
#define RDM_OID_DEV_INFO_MEM_STAT                15396	/*Device.DeviceInfo.MemoryStatus*/
#define RDM_OID_DEV_INFO_PS_STAT                 15480	/*Device.DeviceInfo.ProcessStatus*/
#define RDM_OID_DEV_INFO_PS_STAT_PS              15564	/*Device.DeviceInfo.ProcessStatus.Process.i*/
#define RDM_OID_TEMP_STAT                        15744	/*Device.DeviceInfo.TemperatureStatus*/
#define RDM_OID_TEMP_STAT_TEMP_SENSOR            15804	/*Device.DeviceInfo.TemperatureStatus.TemperatureSensor.i*/
#define RDM_OID_NETWORK_PROP                     16248	/*Device.DeviceInfo.NetworkProperties.i*/
#define RDM_OID_DEV_INFO_PROCESSOR               16332	/*Device.DeviceInfo.Processor.i*/
#define RDM_OID_DEV_INFO_VENDOR_LOG_FILE         16416	/*Device.DeviceInfo.VendorLogFile.i*/
#define RDM_OID_DEV_INFO_PROXIER_INFO            16548	/*Device.DeviceInfo.ProxierInfo.i*/
#define RDM_OID_DEV_INFO_LOC                     16680	/*Device.DeviceInfo.Location.i*/
#define RDM_OID_MGMT_SRV                         16836	/*Device.ManagementServer*/
#define RDM_OID_MGMT_SRV_MGAB_DEV                18480	/*Device.ManagementServer.ManageableDevice.i*/
#define RDM_OID_MGMT_SRV_AUTO_TRANS_COMPLETE_POL 18660	/*Device.ManagementServer.AutonomousTransferCompletePolicy*/
#define RDM_OID_MGMT_SRV_DL_AVAIL                18792	/*Device.ManagementServer.DownloadAvailability*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_ANNCMNT        18828	/*Device.ManagementServer.DownloadAvailability.Announcement*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_ANNCMNT_GROUP  18936	/*Device.ManagementServer.DownloadAvailability.Announcement.Group.i*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_QUERY          19068	/*Device.ManagementServer.DownloadAvailability.Query*/
#define RDM_OID_MGMT_SRV_DU_STATE_CHANGE_COMPL_POL 19176	/*Device.ManagementServer.DUStateChangeComplPolicy*/
#define RDM_OID_MGMT_SRV_EMBEDED_DEV             19308	/*Device.ManagementServer.EmbeddedDevice.i*/
#define RDM_OID_MGMT_SRV_VIRTUAL_DEV             19560	/*Device.ManagementServer.VirtualDevice.i*/
#define RDM_OID_GATEWAY_INFO                     19716	/*Device.GatewayInfo*/
#define RDM_OID_TIME                             19824	/*Device.Time*/
#define RDM_OID_USR_INTF                         20484	/*Device.UserInterface*/
#define RDM_OID_USR_INTF_REMO_ACESS              21096	/*Device.UserInterface.RemoteAccess*/
#define RDM_OID_USR_INTF_LOCAL_DISP              21228	/*Device.UserInterface.LocalDisplay*/
#define RDM_OID_IFACE_STACK                      21456	/*Device.InterfaceStack.i*/
#define RDM_OID_DSL                              21612	/*Device.DSL*/
#define RDM_OID_DSL_LINE                         21720	/*Device.DSL.Line.i*/
#define RDM_OID_DSL_LINE_ST                      25668	/*Device.DSL.Line.i.Stats*/
#define RDM_OID_DSL_LINE_ST_TOTAL                26016	/*Device.DSL.Line.i.Stats.Total*/
#define RDM_OID_DSL_LINE_ST_SHOWTIME             26508	/*Device.DSL.Line.i.Stats.Showtime*/
#define RDM_OID_DSL_LINE_ST_LAST_SHOWTIME        27000	/*Device.DSL.Line.i.Stats.LastShowtime*/
#define RDM_OID_DSL_LINE_ST_LAST_CUR_DAY         27084	/*Device.DSL.Line.i.Stats.CurrentDay*/
#define RDM_OID_DSL_LINE_ST_LAST_QUAR_HR         27576	/*Device.DSL.Line.i.Stats.QuarterHour*/
#define RDM_OID_DSL_LINE_TEST_PARAMS             27660	/*Device.DSL.Line.i.TestParams*/
#define RDM_OID_DSL_CHANNEL                      28224	/*Device.DSL.Channel.i*/
#define RDM_OID_DSL_CHANNEL_ST                   28716	/*Device.DSL.Channel.i.Stats*/
#define RDM_OID_DSL_CHANNEL_ST_TOTAL             29064	/*Device.DSL.Channel.i.Stats.Total*/
#define RDM_OID_DSL_CHANNEL_ST_SHOWTIME          29244	/*Device.DSL.Channel.i.Stats.Showtime*/
#define RDM_OID_DSL_CHANNEL_ST_LAST_SHOWTIME     29424	/*Device.DSL.Channel.i.Stats.LastShowtime*/
#define RDM_OID_DSL_CHANNEL_ST_CUR_DAY           29604	/*Device.DSL.Channel.i.Stats.CurrentDay*/
#define RDM_OID_DSL_CHANNEL_ST_QUAR_HR           29784	/*Device.DSL.Channel.i.Stats.QuarterHour*/
#define RDM_OID_DSL_BOND_GP                      29964	/*Device.DSL.BondingGroup.i*/
#define RDM_OID_DSL_BOND_GP_BONDED_CHANNEL       30480	/*Device.DSL.BondingGroup.i.BondedChannel.i*/
#define RDM_OID_DSL_BOND_GP_BONDED_CHANNEL_ETH   30564	/*Device.DSL.BondingGroup.i.BondedChannel.i.Ethernet*/
#define RDM_OID_DSL_BOND_GP_BONDED_CHANNEL_ETH_ST 30600	/*Device.DSL.BondingGroup.i.BondedChannel.i.Ethernet.Stats*/
#define RDM_OID_DSL_BOND_GP_ST                   30828	/*Device.DSL.BondingGroup.i.Stats*/
#define RDM_OID_DSL_BOND_GP_ST_TOTAL             31296	/*Device.DSL.BondingGroup.i.Stats.Total*/
#define RDM_OID_DSL_BOND_GP_ST_CURRENT_DAY       31596	/*Device.DSL.BondingGroup.i.Stats.CurrentDay*/
#define RDM_OID_DSL_BOND_GP_ST_QTR_HR            31896	/*Device.DSL.BondingGroup.i.Stats.QuarterHour*/
#define RDM_OID_DSL_BOND_GP_ETH                  32196	/*Device.DSL.BondingGroup.i.Ethernet*/
#define RDM_OID_DSL_BOND_GP_ETH_ST               32232	/*Device.DSL.BondingGroup.i.Ethernet.Stats*/
#define RDM_OID_DSL_DIAG                         32652	/*Device.DSL.Diagnostics*/
#define RDM_OID_DSL_DIAG_ADSL_LINE_TEST          32688	/*Device.DSL.Diagnostics.ADSLLineTest*/
#define RDM_OID_OPT                              33588	/*Device.Optical*/
#define RDM_OID_OPT_INTF                         33648	/*Device.Optical.Interface.i*/
#define RDM_OID_OPT_INTF_ST                      33996	/*Device.Optical.Interface.i.Stats*/
#define RDM_OID_ATM                              34224	/*Device.ATM*/
#define RDM_OID_ATM_LINK                         34284	/*Device.ATM.Link.i*/
#define RDM_OID_ATM_LINK_ST                      34824	/*Device.ATM.Link.i.Stats*/
#define RDM_OID_ATM_LINK_QOS                     35316	/*Device.ATM.Link.i.QoS*/
#define RDM_OID_ATM_DIAG                         35472	/*Device.ATM.Diagnostics*/
#define RDM_OID_ATM_DIAG_F5_LO                   35508	/*Device.ATM.Diagnostics.F5Loopback*/
#define RDM_OID_ATM_DIAG_F4_LO                   35808	/*Device.ATM.Diagnostics.X_ZYXEL_F4Loopback*/
#define RDM_OID_PTM                              36108	/*Device.PTM*/
#define RDM_OID_PTM_LINK                         36168	/*Device.PTM.Link.i*/
#define RDM_OID_PTM_LINK_ST                      36732	/*Device.PTM.Link.i.Stats*/
#define RDM_OID_ETH                              37128	/*Device.Ethernet*/
#define RDM_OID_ETH_RMON_ST                      37260	/*Device.Ethernet.RMONStats.i*/
#define RDM_OID_ETH_IFACE                        37824	/*Device.Ethernet.Interface.i*/
#define RDM_OID_ETH_INTF_ST                      38220	/*Device.Ethernet.Interface.i.Stats*/
#define RDM_OID_ETH_LINK                         38616	/*Device.Ethernet.Link.i*/
#define RDM_OID_ETH_LINK_ST                      38940	/*Device.Ethernet.Link.i.Stats*/
#define RDM_OID_ETH_VLAN_TERM                    39336	/*Device.Ethernet.VLANTermination.i*/
#define RDM_OID_ETH_VLAN_TERM_ST                 39636	/*Device.Ethernet.VLANTermination.i.Stats*/
#define RDM_OID_USB                              40032	/*Device.USB*/
#define RDM_OID_USB_INTF                         40116	/*Device.USB.Interface.i*/
#define RDM_OID_USB_INTF_STAT                    40416	/*Device.USB.Interface.i.Stats*/
#define RDM_OID_USB_PORT                         40812	/*Device.USB.Port.i*/
#define RDM_OID_USB_USBHOSTS                     41040	/*Device.USB.USBHosts*/
#define RDM_OID_USB_USBHOSTS_HOST                41100	/*Device.USB.USBHosts.Host.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV            41328	/*Device.USB.USBHosts.Host.i.Device.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_PAR        41844	/*Device.USB.USBHosts.Host.i.Device.i.X_ZYXEL_Partition.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_CFG        41952	/*Device.USB.USBHosts.Host.i.Device.i.Configuration.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_CFG_INTF   42036	/*Device.USB.USBHosts.Host.i.Device.i.Configuration.i.Interface.i*/
#define RDM_OID_CELLULAR                         42168	/*Device.Cellular*/
#define RDM_OID_CELLULAR_INTERFACE               42276	/*Device.Cellular.Interface.i*/
#define RDM_OID_CELLULAR_IFACE_U_S_I_M           42624	/*Device.Cellular.Interface.i.USIM*/
#define RDM_OID_CELLULAR_ACCESS_POINT            42732	/*Device.Cellular.AccessPoint.i*/
#define RDM_OID_HPNA                             42960	/*Device.HPNA*/
#define RDM_OID_HPNA_INTF                        43020	/*Device.HPNA.Interface.i*/
#define RDM_OID_HPNA_INTF_ST                     43704	/*Device.HPNA.Interface.i.Stats*/
#define RDM_OID_HPNA_INTF_QOS                    44100	/*Device.HPNA.Interface.i.QoS*/
#define RDM_OID_HPNA_INTF_QOS_FLOW_SPEC          44160	/*Device.HPNA.Interface.i.QoS.FlowSpec.i*/
#define RDM_OID_HPNA_INTF_ASSOC_DEV              44532	/*Device.HPNA.Interface.i.AssociatedDevice.i*/
#define RDM_OID_HPNA_DIAG                        44760	/*Device.HPNA.Diagnostics*/
#define RDM_OID_HPNA_DIAG_PHY_THROUGHPUT         44796	/*Device.HPNA.Diagnostics.PHYThroughput*/
#define RDM_OID_HPNA_DIAG_PHY_THROUGHPUT_RESULT  45072	/*Device.HPNA.Diagnostics.PHYThroughput.Result.i*/
#define RDM_OID_HPNA_DIAG_PERF_MONT              45276	/*Device.HPNA.Diagnostics.PerformanceMonitoring*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_NODES     45384	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Nodes*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_NODES_NODE 45492	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Nodes.Node.i*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_CHANNELS  46128	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Channels*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_CHANNELS_CHANNEL 46212	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Channels.Channel.i*/
#define RDM_OID_MOCA                             46512	/*Device.MoCA*/
#define RDM_OID_MOCA_INTF                        46572	/*Device.MoCA.Interface.i*/
#define RDM_OID_MOCA_INTF_ST                     47472	/*Device.MoCA.Interface.i.Stats*/
#define RDM_OID_MOCA_INTF_QOS                    47868	/*Device.MoCA.Interface.i.QoS*/
#define RDM_OID_MOCA_INTF_QOS_FLOW_ST            47976	/*Device.MoCA.Interface.i.QoS.FlowStats.i*/
#define RDM_OID_MOCA_INTF_ASSOC_DEV              48156	/*Device.MoCA.Interface.i.AssociatedDevice.i*/
#define RDM_OID_GHN                              48600	/*Device.Ghn*/
#define RDM_OID_GHN_INTF                         48660	/*Device.Ghn.Interface.i*/
#define RDM_OID_GHN_INTF_ST                      49224	/*Device.Ghn.Interface.i.Stats*/
#define RDM_OID_GHN_INTF_ASSOC_DEV               49620	/*Device.Ghn.Interface.i.AssociatedDevice.i*/
#define RDM_OID_HOME_PLUG                        49776	/*Device.Homeplug*/
#define RDM_OID_HOMEPLUG_INTF                    49836	/*Device.Homeplug.Interface.i*/
#define RDM_OID_HOMEPLUG_INTF_ST                 50256	/*Device.Homeplug.Interface.i.Stats*/
#define RDM_OID_HOMEPLUG_INTF_ASSOC_DEV          50772	/*Device.Homeplug.Interface.i.AssociatedDevice.i*/
#define RDM_OID_UPA                              50976	/*Device.UPA*/
#define RDM_OID_UPA_INTF                         51036	/*Device.UPA.Interface.i*/
#define RDM_OID_UPA_INTF_ST                      51576	/*Device.UPA.Interface.i.Stats*/
#define RDM_OID_UPA_INTF_ASSOC_DEV               51972	/*Device.UPA.Interface.i.AssociatedDevice.i*/
#define RDM_OID_UPA_INTF_ACTIVE_NOTCH            52272	/*Device.UPA.Interface.i.ActiveNotch.i*/
#define RDM_OID_UPA_INTF_BRIDGE_FOR              52428	/*Device.UPA.Interface.i.BridgeFor.i*/
#define RDM_OID_UPA_DIAG                         52536	/*Device.UPA.Diagnostics*/
#define RDM_OID_UPA_DIAG_INTF_MEASUREMENT        52572	/*Device.UPA.Diagnostics.InterfaceMeasurement*/
#define RDM_OID_WIFI                             52752	/*Device.WiFi*/
#define RDM_OID_WIFI_ONE_SSID                    52908	/*Device.WiFi.X_ZYXEL_OneSSID*/
#define RDM_OID_WIFI_RADIO                       52968	/*Device.WiFi.Radio.i*/
#define RDM_OID_WIFI_RADIO_ST                    54612	/*Device.WiFi.Radio.i.Stats*/
#define RDM_OID_WIFI_SSID                        54864	/*Device.WiFi.SSID.i*/
#define RDM_OID_WIFI_SSID_STAT                   55404	/*Device.WiFi.SSID.i.Stats*/
#define RDM_OID_WIFI_ACCESS_POINT                55800	/*Device.WiFi.AccessPoint.i*/
#define RDM_OID_WIFI_ACCESS_POINT_SEC            56172	/*Device.WiFi.AccessPoint.i.Security*/
#define RDM_OID_WIFI_ACCESS_POINT_ACCOUNTING     57192	/*Device.WiFi.AccessPoint.i.Accounting*/
#define RDM_OID_WIFI_ACCESS_POINT_WPS            57420	/*Device.WiFi.AccessPoint.i.WPS*/
#define RDM_OID_WIFI_ACCESS_POINT_ASSOC_DEV      57816	/*Device.WiFi.AccessPoint.i.AssociatedDevice.i*/
#define RDM_OID_WIFI_ACCESS_POINT_ASSOC_DEV_ST   58092	/*Device.WiFi.AccessPoint.i.AssociatedDevice.i.Stats*/
#define RDM_OID_WIFI_STA_FILTER                  58344	/*Device.WiFi.AccessPoint.i.StationFilter*/
#define RDM_OID_WIFI_END_POINT                   58428	/*Device.WiFi.EndPoint.i*/
#define RDM_OID_WIFI_END_POINT_ST                58608	/*Device.WiFi.EndPoint.i.Stats*/
#define RDM_OID_WIFI_END_POINT_SEC               58740	/*Device.WiFi.EndPoint.i.Security*/
#define RDM_OID_WIFI_END_POINT_PROFILE           58800	/*Device.WiFi.EndPoint.i.Profile.i*/
#define RDM_OID_WIFI_END_POINT_PROFILE_SEC       58980	/*Device.WiFi.EndPoint.i.Profile.i.Security*/
#define RDM_OID_WPS                              59112	/*Device.WiFi.EndPoint.i.WPS*/
#define RDM_OID_WIFI_DIAGNOSTIC                  59220	/*Device.WiFi.NeighboringWiFiDiagnostic*/
#define RDM_OID_WIFI_DIAGNOSTIC_RESULTS          59328	/*Device.WiFi.NeighboringWiFiDiagnostic.Result.i*/
#define RDM_OID_WIFI_AP_STEERING                 59772	/*Device.WiFi.X_ZYXEL_ApSteering*/
#define RDM_OID_WLAN_SCHEDULER                   60216	/*Device.WiFi.X_ZYXEL_WLAN_Scheduler.i*/
#define RDM_OID_BRIDGING                         60540	/*Device.Bridging*/
#define RDM_OID_BRIDGING_BR                      60816	/*Device.Bridging.Bridge.i*/
#define RDM_OID_BRIDGING_BR_PORT                 61116	/*Device.Bridging.Bridge.i.Port.i*/
#define RDM_OID_BRIDGING_BR_PORT_ST              61584	/*Device.Bridging.Bridge.i.Port.i.Stats*/
#define RDM_OID_BRIDGING_BR_VLAN                 61980	/*Device.Bridging.Bridge.i.VLAN.i*/
#define RDM_OID_BRIDGING_BR_VLANPORT             62112	/*Device.Bridging.Bridge.i.VLANPort.i*/
#define RDM_OID_BRIDGING_FILTER                  62268	/*Device.Bridging.Filter.i*/
#define RDM_OID_PPP                              63096	/*Device.PPP*/
#define RDM_OID_PPP_IFACE                        63180	/*Device.PPP.Interface.i*/
#define RDM_OID_PPP_IFACE_PPPOA                  64128	/*Device.PPP.Interface.i.PPPoA*/
#define RDM_OID_PPP_IFACE_PPPOE                  64164	/*Device.PPP.Interface.i.PPPoE*/
#define RDM_OID_PPP_IFACE_IPCP                   64296	/*Device.PPP.Interface.i.IPCP*/
#define RDM_OID_PPP_INTF_IPV6CP                  64452	/*Device.PPP.Interface.i.IPV6CP*/
#define RDM_OID_PPP_IFACE_STAT                   64536	/*Device.PPP.Interface.i.Stats*/
#define RDM_OID_IP                               64932	/*Device.IP*/
#define RDM_OID_IP_IFACE                         65184	/*Device.IP.Interface.i*/
#define RDM_OID_IP_IFACE_V4_ADDR                 66636	/*Device.IP.Interface.i.IPv4Address.i*/
#define RDM_OID_IP_IFACE_V6_ADDR                 66888	/*Device.IP.Interface.i.IPv6Address.i*/
#define RDM_OID_IP_IFACE_V6_PREFIX               67260	/*Device.IP.Interface.i.IPv6Prefix.i*/
#define RDM_OID_IP_IFACE_STAT                    67704	/*Device.IP.Interface.i.Stats*/
#define RDM_OID_IP_ACTIVE_PORT                   68100	/*Device.IP.ActivePort.i*/
#define RDM_OID_IP_DIAG                          68256	/*Device.IP.Diagnostics*/
#define RDM_OID_IP_DIAG_IPPING                   68292	/*Device.IP.Diagnostics.IPPing*/
#define RDM_OID_IP_DIAG_TRACE_RT                 68736	/*Device.IP.Diagnostics.TraceRoute*/
#define RDM_OID_IP_DIAG_TRACERT_RT_HOPS          69060	/*Device.IP.Diagnostics.TraceRoute.RouteHops.i*/
#define RDM_OID_IP_DIAG_DL_DIAG                  69192	/*Device.IP.Diagnostics.DownloadDiagnostics*/
#define RDM_OID_IP_DIAG_UL_DIAG                  69660	/*Device.IP.Diagnostics.UploadDiagnostics*/
#define RDM_OID_IP_DIAG_UDP_ECHO_CFG             70080	/*Device.IP.Diagnostics.UDPEchoConfig*/
#define RDM_OID_IP_DIAG_UDP_ECHO_DIAG            70404	/*Device.IP.Diagnostics.UDPEchoDiagnostics*/
#define RDM_OID_IP_DIAG_UDP_ECHO_PAK_RST         70920	/*Device.IP.Diagnostics.UDPEchoDiagnostics.IndividualPacketResult.i*/
#define RDM_OID_IP_DIAG_SVR_SELECT_DIAG          71148	/*Device.IP.Diagnostics.ServerSelectionDiagnostics*/
#define RDM_OID_IPSEC                            71472	/*Device.IPSec*/
#define RDM_OID_IPSEC_STAT                       71844	/*Device.IPSec.Stats*/
#define RDM_OID_IPSEC_FILTER                     72168	/*Device.IPSec.Filter.i*/
#define RDM_OID_IPSEC_PROFILE                    72732	/*Device.IPSec.Profile.i*/
#define RDM_OID_IPSEC_PROFILE_SENT_CP_ATTR       73368	/*Device.IPSec.Profile.i.SentCPAttr.i*/
#define RDM_OID_IPSEC_TUNNEL                     73500	/*Device.IPSec.Tunnel.i*/
#define RDM_OID_IPSEC_TUNNEL_STAT                73632	/*Device.IPSec.Tunnel.i.Stats*/
#define RDM_OID_IPSEC_IKEV2SA                    73788	/*Device.IPSec.IKEv2SA.i*/
#define RDM_OID_IPSEC_IKEV2SA_STAT               74136	/*Device.IPSec.IKEv2SA.i.Stats*/
#define RDM_OID_IPSEC_IKEV2SA_RECEIVED_CP_ATTR   74364	/*Device.IPSec.IKEv2SA.i.ReceivedCPAttr.i*/
#define RDM_OID_IPSEC_IKEV2SA_CHILD_SA           74448	/*Device.IPSec.IKEv2SA.i.ChildSA.i*/
#define RDM_OID_IPSEC_IKEV2SA_CHILD_SA_STAT      74604	/*Device.IPSec.IKEv2SA.i.ChildSA.i.Stats*/
#define RDM_OID_GRE                              74880	/*Device.GRE*/
#define RDM_OID_GRE_TUNNEL                       74964	/*Device.GRE.Tunnel.i*/
#define RDM_OID_GRE_TUNNEL_STAT                  75264	/*Device.GRE.Tunnel.i.Stats*/
#define RDM_OID_GRE_TUNNEL_IFACE                 75492	/*Device.GRE.Tunnel.i.Interface.i*/
#define RDM_OID_GRE_TUNNEL_IFACE_STAT            75792	/*Device.GRE.Tunnel.i.Interface.i.Stats*/
#define RDM_OID_GRE_FILTER                       76020	/*Device.GRE.Filter.i*/
#define RDM_OID_CAPT_PORTAL                      76272	/*Device.CaptivePortal*/
#define RDM_OID_ROUTING                          76404	/*Device.Routing*/
#define RDM_OID_ROUTING_ROUTER                   76464	/*Device.Routing.Router.i*/
#define RDM_OID_ROUTING_ROUTER_V4_FWD            76692	/*Device.Routing.Router.i.IPv4Forwarding.i*/
#define RDM_OID_ROUTING_ROUTER_V6_FWD            77208	/*Device.Routing.Router.i.IPv6Forwarding.i*/
#define RDM_OID_ROUTING_RIP                      77484	/*Device.Routing.RIP*/
#define RDM_OID_ROUTING_RIP_INTF_SET             77592	/*Device.Routing.RIP.InterfaceSetting.i*/
#define RDM_OID_ROUTING_RT_INFO                  77844	/*Device.Routing.RouteInformation*/
#define RDM_OID_ROUTING_RT_INFO_INTF_SET         77928	/*Device.Routing.RouteInformation.InterfaceSetting.i*/
#define RDM_OID_NEIGHBOR_DISCOVERY               78180	/*Device.NeighborDiscovery*/
#define RDM_OID_NEIGHBOR_DISCOVERY_INTF_SET      78264	/*Device.NeighborDiscovery.InterfaceSetting.i*/
#define RDM_OID_RT_ADV                           78564	/*Device.RouterAdvertisement*/
#define RDM_OID_RT_ADV_INTF_SET                  78648	/*Device.RouterAdvertisement.InterfaceSetting.i*/
#define RDM_OID_RT_ADV_INTF_SET_OPT              79236	/*Device.RouterAdvertisement.InterfaceSetting.i.Option.i*/
#define RDM_OID_IPV6RD                           79368	/*Device.IPv6rd*/
#define RDM_OID_IPV6RD_INTF                      79452	/*Device.IPv6rd.InterfaceSetting.i*/
#define RDM_OID_DS_LITE                          79752	/*Device.DSLite*/
#define RDM_OID_DS_LITE_INTF_SET                 79836	/*Device.DSLite.InterfaceSetting.i*/
#define RDM_OID_QOS                              80184	/*Device.QoS*/
#define RDM_OID_QOS_CLS                          80796	/*Device.QoS.Classification.i*/
#define RDM_OID_QOS_APP                          82920	/*Device.QoS.App.i*/
#define RDM_OID_QOS_FLOW                         83196	/*Device.QoS.Flow.i*/
#define RDM_OID_QOS_POLICER                      83520	/*Device.QoS.Policer.i*/
#define RDM_OID_QOS_QUE                          84084	/*Device.QoS.Queue.i*/
#define RDM_OID_QOS_QUE_STAT                     84624	/*Device.QoS.QueueStats.i*/
#define RDM_OID_QOS_SHAPER                       84924	/*Device.QoS.Shaper.i*/
#define RDM_OID_LAN_CONF_SEC                     85104	/*Device.LANConfigSecurity*/
#define RDM_OID_HOSTS                            85164	/*Device.Hosts*/
#define RDM_OID_HOSTS_HOST                       85224	/*Device.Hosts.Host.i*/
#define RDM_OID_HOSTS_HOST_V4_ADDR               86028	/*Device.Hosts.Host.i.IPv4Address.i*/
#define RDM_OID_HOSTS_HOST_V6_ADDR               86088	/*Device.Hosts.Host.i.IPv6Address.i*/
#define RDM_OID_ZY_HOSTS_HOST_EXT                86148	/*Device.Hosts.Host.i.X_ZYXEL_EXT*/
#define RDM_OID_DNS                              86448	/*Device.DNS*/
#define RDM_OID_DNS_CLIENT                       86556	/*Device.DNS.Client*/
#define RDM_OID_DNS_CLIENT_SRV                   86664	/*Device.DNS.Client.Server.i*/
#define RDM_OID_DNS_RELAY                        86940	/*Device.DNS.Relay*/
#define RDM_OID_DNS_RELAY_FWD                    87048	/*Device.DNS.Relay.Forwarding.i*/
#define RDM_OID_DNS_DIAG                         87228	/*Device.DNS.Diagnostics*/
#define RDM_OID_DNS_DIAG_NS_LOOKUP_DIAG          87264	/*Device.DNS.Diagnostics.NSLookupDiagnostics*/
#define RDM_OID_DNS_DIAG_NS_LOOKUP_DIAG_RESULT   87516	/*Device.DNS.Diagnostics.NSLookupDiagnostics.Result.i*/
#define RDM_OID_NAT                              87696	/*Device.NAT*/
#define RDM_OID_NAT_INTF_SETTING                 87924	/*Device.NAT.InterfaceSetting.i*/
#define RDM_OID_NAT_PORT_MAPPING                 88080	/*Device.NAT.PortMapping.i*/
#define RDM_OID_NAT_PORT_TRIGGERING              88620	/*Device.NAT.X_ZYXEL_PortTriggering.i*/
#define RDM_OID_NAT_ADDR_MAPPING                 88920	/*Device.NAT.X_ZYXEL_AddrMapping.i*/
#define RDM_OID_NAT_SESSION_CTL                  89220	/*Device.NAT.X_ZYXEL_SessionControl*/
#define RDM_OID_DHCPV4                           89304	/*Device.DHCPv4*/
#define RDM_OID_DHCPV4_CLIENT                    89364	/*Device.DHCPv4.Client.i*/
#define RDM_OID_DHCPV4_SENT_OPT                  89832	/*Device.DHCPv4.Client.i.SentOption.i*/
#define RDM_OID_DHCPV4_REQ_OPT                   89964	/*Device.DHCPv4.Client.i.ReqOption.i*/
#define RDM_OID_DHCPV4_SRV                       90120	/*Device.DHCPv4.Server*/
#define RDM_OID_DHCPV4_SRV_POOL                  90204	/*Device.DHCPv4.Server.Pool.i*/
#define RDM_OID_DHCPV4_SRV_POOL_STATIC_ADDR      91056	/*Device.DHCPv4.Server.Pool.i.StaticAddress.i*/
#define RDM_OID_DHCPV4_SRV_POOL_OPT              91188	/*Device.DHCPv4.Server.Pool.i.Option.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT           91320	/*Device.DHCPv4.Server.Pool.i.Client.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT_V4_ADDR   91476	/*Device.DHCPv4.Server.Pool.i.Client.i.IPv4Address.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT_OPT       91560	/*Device.DHCPv4.Server.Pool.i.Client.i.Option.i*/
#define RDM_OID_DHCPV4_SRV_SUBNET                91644	/*Device.DHCPv4.Server.X_ZYXEL_Subnet.i*/
#define RDM_OID_DHCPV4_RELAY                     91824	/*Device.DHCPv4.Relay*/
#define RDM_OID_DHCPV4_RELAY_FWD                 91932	/*Device.DHCPv4.Relay.Forwarding.i*/
#define RDM_OID_DHCPV6                           92376	/*Device.DHCPv6*/
#define RDM_OID_DHCPV6_CLIENT                    92436	/*Device.DHCPv6.Client.i*/
#define RDM_OID_DHCPV6_CLIENT_SRV                92880	/*Device.DHCPv6.Client.i.Server.i*/
#define RDM_OID_DHCPV6_CLIENT_SENT_OPT           92988	/*Device.DHCPv6.Client.i.SentOption.i*/
#define RDM_OID_DHCPV6_CLIENT_RECEIVED_OPT       93120	/*Device.DHCPv6.Client.i.ReceivedOption.i*/
#define RDM_OID_DHCPV6_SRV                       93228	/*Device.DHCPv6.Server*/
#define RDM_OID_DHCPV6_SRV_POOL                  93312	/*Device.DHCPv6.Server.Pool.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT           94044	/*Device.DHCPv6.Server.Pool.i.Client.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_V6_ADDR   94224	/*Device.DHCPv6.Server.Pool.i.Client.i.IPv6Address.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_V6_PREFIX 94332	/*Device.DHCPv6.Server.Pool.i.Client.i.IPv6Prefix.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_OPT       94440	/*Device.DHCPv6.Server.Pool.i.Client.i.Option.i*/
#define RDM_OID_DHCPV6_SRV_POOL_OPT              94524	/*Device.DHCPv6.Server.Pool.i.Option.i*/
#define RDM_OID_IEEE8021X                        94680	/*Device.IEEE8021x*/
#define RDM_OID_IEEE8021X_SUPPLICANT             94740	/*Device.IEEE8021x.Supplicant.i*/
#define RDM_OID_IEEE8021X_SUPPLICANT_STAT        95208	/*Device.IEEE8021x.Supplicant.i.Stats*/
#define RDM_OID_IEEE8021X_SUPPLICANT_EAPMD5      95508	/*Device.IEEE8021x.Supplicant.i.EAPMD5*/
#define RDM_OID_IEEE8021X_SUPPLICANT_EAPTLS      95592	/*Device.IEEE8021x.Supplicant.i.EAPTLS*/
#define RDM_OID_USRS                             95676	/*Device.Users*/
#define RDM_OID_USRS_USR                         95736	/*Device.Users.User.i*/
#define RDM_OID_SMART_CARD_READERS               95916	/*Device.SmartCardReaders*/
#define RDM_OID_SMART_CARD_READERS_SCR           95976	/*Device.SmartCardReaders.SmartCardReader.i*/
#define RDM_OID_SMART_CARD_READERS_SCR_SC        96204	/*Device.SmartCardReaders.SmartCardReader.i.SmartCard*/
#define RDM_OID_UPNP                             96360	/*Device.UPnP*/
#define RDM_OID_UPNP_DEV                         96396	/*Device.UPnP.Device*/
#define RDM_OID_UPNP_DEV_CAPB                    96720	/*Device.UPnP.Device.Capabilities*/
#define RDM_OID_UPNP_DISC                        97044	/*Device.UPnP.Discovery*/
#define RDM_OID_UPNP_DISC_ROOT_DEV               97152	/*Device.UPnP.Discovery.RootDevice.i*/
#define RDM_OID_UPNP_DISC_DEV                    97356	/*Device.UPnP.Discovery.Device.i*/
#define RDM_OID_UPNP_DISC_SERVICE                97560	/*Device.UPnP.Discovery.Service.i*/
#define RDM_OID_DLNA                             97740	/*Device.DLNA*/
#define RDM_OID_DLNA_CAPB                        97920	/*Device.DLNA.Capabilities*/
#define RDM_OID_SELF_TEST_DIAG                   98148	/*Device.SelfTestDiagnostics*/
#define RDM_OID_FIREWALL                         98232	/*Device.Firewall*/
#define RDM_OID_FIREWALL_LEVEL                   98556	/*Device.Firewall.Level.i*/
#define RDM_OID_FIREWALL_CHAIN                   98808	/*Device.Firewall.Chain.i*/
#define RDM_OID_FIREWALL_CHAIN_RULE              98964	/*Device.Firewall.Chain.i.Rule.i*/
#define RDM_OID_PERD_STATISTICS                  100008	/*Device.PeriodicStatistics*/
#define RDM_OID_PERD_STATISTICS_SAMPLE_SET       100116	/*Device.PeriodicStatistics.SampleSet.i*/
#define RDM_OID_PERD_STATISTICS_SAMPLE_SET_PARAM 100464	/*Device.PeriodicStatistics.SampleSet.i.Parameter.i*/
#define RDM_OID_SW_MODULE                        100764	/*Device.SoftwareModules*/
#define RDM_OID_SW_MODULE_EXEC_ENV               100872	/*Device.SoftwareModules.ExecEnv.i*/
#define RDM_OID_SW_MODULE_DEPLOYMENT_UNIT        101364	/*Device.SoftwareModules.DeploymentUnit.i*/
#define RDM_OID_SW_MODULE_EXEC_UNIT              101736	/*Device.SoftwareModules.ExecutionUnit*/
#define RDM_OID_SW_MODULE_EXEC_UNIT_EXT          102276	/*Device.SoftwareModules.ExecutionUnit.Extensions*/
#define RDM_OID_FAULT_MGMT                       102312	/*Device.FaultMgmt*/
#define RDM_OID_FAULT_MGMT_SUPT_ALARM            102492	/*Device.FaultMgmt.SupportedAlarm.i*/
#define RDM_OID_FAULT_MGMT_CURRENT_ALARM         102648	/*Device.FaultMgmt.CurrentAlarm.i*/
#define RDM_OID_FAULT_MGMT_HISTORY_EVENT         102924	/*Device.FaultMgmt.HistoryEvent.i*/
#define RDM_OID_FAULT_MGMT_EXPEDITED_EVENT       103200	/*Device.FaultMgmt.ExpeditedEvent.i*/
#define RDM_OID_FAULT_MGMT_QUED_EVENT            103476	/*Device.FaultMgmt.QueuedEvent.i*/
#define RDM_OID_DEV_SEC                          103752	/*Device.Security*/
#define RDM_OID_DEV_SEC_CERT                     103812	/*Device.Security.Certificate.i*/
#define RDM_OID_FAP                              104280	/*Device.FAP*/
#define RDM_OID_FAP_GPS                          104316	/*Device.FAP.GPS*/
#define RDM_OID_FAP_GPS_CONTS_GPS_STATUS         104688	/*Device.FAP.GPS.ContinuousGPSStatus*/
#define RDM_OID_FAP_GPS_AGPS_SRV_CONF            105060	/*Device.FAP.GPS.AGPSServerConfig*/
#define RDM_OID_FAP_PERF_MGMT                    105288	/*Device.FAP.PerfMgmt*/
#define RDM_OID_FAP_PERF_MGMT_CONF               105348	/*Device.FAP.PerfMgmt.Config.i*/
#define RDM_OID_FAP_APP_PLATF                    105552	/*Device.FAP.ApplicationPlatform*/
#define RDM_OID_FAP_APP_PLATF_CAPB               105708	/*Device.FAP.ApplicationPlatform.Capabilities*/
#define RDM_OID_FAP_APP_PLATF_CTRL               106056	/*Device.FAP.ApplicationPlatform.Control*/
#define RDM_OID_FAP_APP_PLATF_CTRL_FEMTO_AWARE   106140	/*Device.FAP.ApplicationPlatform.Control.FemtoAwareness*/
#define RDM_OID_FAP_APP_PLATF_CTRL_SMS           106368	/*Device.FAP.ApplicationPlatform.Control.SMS*/
#define RDM_OID_FAP_APP_PLATF_CTRL_MMS           106572	/*Device.FAP.ApplicationPlatform.Control.MMS*/
#define RDM_OID_FAP_APP_PLATF_CTRL_TERM_LOC      106776	/*Device.FAP.ApplicationPlatform.Control.TerminalLocation*/
#define RDM_OID_FAP_APP_PLATF_MONT               107004	/*Device.FAP.ApplicationPlatform.Monitoring*/
#define RDM_OID_FAP_APP_PLATF_MONT_FEMTO_AWARE   107136	/*Device.FAP.ApplicationPlatform.Monitoring.FemtoAwareness*/
#define RDM_OID_FAP_APP_PLATF_MONT_SMS           107316	/*Device.FAP.ApplicationPlatform.Monitoring.SMS*/
#define RDM_OID_FAP_APP_PLATF_MONT_MMS           107496	/*Device.FAP.ApplicationPlatform.Monitoring.MMS*/
#define RDM_OID_FAP_APP_PLATF_MONT_TERM_LOC      107676	/*Device.FAP.ApplicationPlatform.Monitoring.TerminalLocation*/
#define RDM_OID_BULK_DATA                        107856	/*Device.BulkData*/
#define RDM_OID_BULK_DATA_PROF                   108084	/*Device.BulkData.Profile.i*/
#define RDM_OID_BULK_DATA_PROF_PARAM             108456	/*Device.BulkData.Profile.i.Parameter.i*/
#define RDM_OID_ROM_CONVERT                      108516	/*Device.X_ZYXEL_RomConvert.i*/
#define RDM_OID_SCHEDULE                         108576	/*Device.X_ZYXEL_Schedule.i*/
#define RDM_OID_EMAIL_NOTIFY                     108852	/*Device.X_ZYXEL_EmailNotification*/
#define RDM_OID_MAIL_SERVICE                     108888	/*Device.X_ZYXEL_EmailNotification.EmailService.i*/
#define RDM_OID_MAIL_EVENT_CFG                   109116	/*Device.X_ZYXEL_EmailNotification.EmailEventConfig.i*/
#define RDM_OID_PAREN_CTL                        109296	/*Device.X_ZYXEL_ParentalControl*/
#define RDM_OID_PAREN_CTL_PROF                   109356	/*Device.X_ZYXEL_ParentalControl.Profile.i*/
#define RDM_OID_IEEE8021AG                       109608	/*Device.X_ZYXEL_8021ag*/
#define RDM_OID_IEEE8023AH                       110100	/*Device.X_ZYXEL_8023ah*/
#define RDM_OID_ZY_EXT                           110352	/*Device.X_ZYXEL_EXT*/
#define RDM_OID_DNS_RT_ENTRY                     110388	/*Device.X_ZYXEL_EXT.DNSRouteEntry.i*/
#define RDM_OID_DNS_ENTRY                        110592	/*Device.X_ZYXEL_EXT.DNSEntry.i*/
#define RDM_OID_D_DNS                            110676	/*Device.X_ZYXEL_EXT.DynamicDNS*/
#define RDM_OID_AUTO_PROV                        111096	/*Device.X_ZYXEL_EXT.AutoProvision*/
#define RDM_OID_SPEED_TEST                       111324	/*Device.X_ZYXEL_EXT.SpeedTestInfo*/
#define RDM_OID_WIFI_QSTEER                      111432	/*Device.X_ZYXEL_EXT.Qsteer*/
#define RDM_OID_ZY_HOST_NAME_REPLACE             111564	/*Device.X_ZYXEL_EXT.HostNameReplace*/
#define RDM_OID_PPTP_CFG                         111624	/*Device.X_ZYXEL_EXT.X_ZYXEL_PPTP_Config*/
#define RDM_OID_ZY_IGMP                          111924	/*Device.X_ZYXEL_IGMP*/
#define RDM_OID_ZY_SNMP                          112368	/*Device.X_ZYXEL_SNMP*/
#define RDM_OID_TRAP_ADDR                        112524	/*Device.X_ZYXEL_SNMP.TrapAddr.i*/
#define RDM_OID_ZY_MLD                           112632	/*Device.X_ZYXEL_MLD*/
#define RDM_OID_ZY_LOG_CFG                       113052	/*Device.X_ZYXEL_LoginCfg*/
#define RDM_OID_ZY_LOG_CFG_GP                    113160	/*Device.X_ZYXEL_LoginCfg.LogGp.i*/
#define RDM_OID_ZY_LOG_CFG_GP_ACCOUNT            113316	/*Device.X_ZYXEL_LoginCfg.LogGp.i.Account.i*/
#define RDM_OID_ZY_MAC_FILTER                    114048	/*Device.X_ZYXEL_MacFilter*/
#define RDM_OID_ZY_MAC_FILTER_WHITE_LIST         114156	/*Device.X_ZYXEL_MacFilter.WhiteList.i*/
#define RDM_OID_WLAN_SCHEDULER_ACCESS            114264	/*Device.X_ZYXEL_WlanSchedulerAccess*/
#define RDM_OID_VC_AUTO_HUNT                     114396	/*Device.X_ZYXEL_VcAutoHunt*/
#define RDM_OID_VC_HUNT_INFO                     114552	/*Device.X_ZYXEL_VcAutoHunt.VcHuntInfo.i*/
#define RDM_OID_VC_HUNT_RULE                     114636	/*Device.X_ZYXEL_VcAutoHunt.VcHuntInfo.i.VcHuntRule.i*/
#define RDM_OID_VLAN_AUTO_HUNT                   114720	/*Device.X_ZYXEL_VlanAutoHunt*/
#define RDM_OID_VLAN_HUNT_INFO                   114852	/*Device.X_ZYXEL_VlanAutoHunt.VlanHuntInfo.i*/
#define RDM_OID_VLAN_HUNT_RULE                   114936	/*Device.X_ZYXEL_VlanAutoHunt.VlanHuntInfo.i.VlanHuntRule.i*/
#define RDM_OID_LANG                             115020	/*Device.X_ZYXEL_Language*/
#define RDM_OID_REMO_MGMT                        115080	/*Device.X_ZYXEL_RemoteManagement*/
#define RDM_OID_REMO_SRV                         115164	/*Device.X_ZYXEL_RemoteManagement.Service.i*/
#define RDM_OID_REMO_SRV_TRUST_DOMAIN            115440	/*Device.X_ZYXEL_RemoteManagement.Service.i.TrustDomain.i*/
#define RDM_OID_SP_REMO_SRV                      115548	/*Device.X_ZYXEL_RemoteManagement.SPService.i*/
#define RDM_OID_SP_REMO_SRV_TRUST_DOMAIN         115824	/*Device.X_ZYXEL_RemoteManagement.SPService.i.TrustDomain.i*/
#define RDM_OID_REMO_MGMT_TRUST_DOMAIN           115956	/*Device.X_ZYXEL_RemoteManagement.TrustDomain.i*/
#define RDM_OID_SP_TRUST_DOMAIN                  116064	/*Device.X_ZYXEL_RemoteManagement.SPTrustDomain.i*/
#define RDM_OID_NETWORK_SRV                      116196	/*Device.X_ZYXEL_NetworkService*/
#define RDM_OID_NETWORK_SRV_GP                   116256	/*Device.X_ZYXEL_NetworkService.Service.i*/
#define RDM_OID_SYSTEM_INFO                      116508	/*Device.X_ZYXEL_System_Info*/
#define RDM_OID_GPON_INFO                        116712	/*Device.X_ZYXEL_GPON_Info*/
#define RDM_OID_LOG_SETTING                      116916	/*Device.X_ZYXEL_Log_Setting*/
#define RDM_OID_LOG_CLASSIFY                     117120	/*Device.X_ZYXEL_Log_Setting.LogClassify.i*/
#define RDM_OID_LOG_CATEGORY                     117228	/*Device.X_ZYXEL_Log_Setting.LogClassify.i.Category.i*/
#define RDM_OID_CHANGE_ICON_NAME                 117408	/*Device.X_ZYXEL_Change_Icon_Name.i*/
#define RDM_OID_PORT_MIRROR                      117540	/*Device.X_ZYXEL_PortMirroring.i*/
#define RDM_OID_VLAN_GROUP                       117672	/*Device.X_ZYXEL_VlanGroup.i*/
#define RDM_OID_S_T_B_VENDOR_I_D                 117852	/*Device.X_ZYXEL_STB_VENDOR_ID*/
#define RDM_OID_T_F_T_P_SRV_NAME                 118008	/*Device.X_ZYXEL_TFTP_SERVER_NAME*/
#define RDM_OID_TR064                            118068	/*Device.X_ZYXEL_TR064*/
#define RDM_OID_ZY_W_W_A_N_BACKUP                118128	/*Device.X_ZYXEL_WWAN_BACKUP*/
#define RDM_OID_ZY_BAND_WIDTH_IMPROVEMENT        118548	/*Device.X_ZYXEL_WWAN_BACKUP.BandWidthImprovement*/
#define RDM_OID_ZY_W_W_A_N_PING_CHECK            118704	/*Device.X_ZYXEL_WWAN_BACKUP.PingCheck*/
#define RDM_OID_ZY_W_W_A_N_BUDGET_CONTROL        118860	/*Device.X_ZYXEL_WWAN_BACKUP.BudgetControl*/
#define RDM_OID_ZY_W_W_A_N_STAT                  119544	/*Device.X_ZYXEL_WWAN_BACKUP.Stats*/
#define RDM_OID_ZY_SAMBA                         119796	/*Device.X_ZYXEL_SAMBA*/
#define RDM_OID_ZY_SAMBA_DIR                     119880	/*Device.X_ZYXEL_SAMBA.Directory.i*/
#define RDM_OID_GUI_CUSTOMIZATION                120132	/*Device.X_ZYXEL_GUI_CUSTOMIZATION*/
#define RDM_OID_INPUT_CHECK_LIST                 120480	/*Device.X_ZYXEL_GUI_CUSTOMIZATION.InputCheckList.i*/
#define RDM_OID_FEATURE_FLAG                     120660	/*Device.X_ZYXEL_FEATRUE_FLAG*/
#define RDM_OID_ZY_OPTION125                     120888	/*Device.X_ZYXEL_Option125VendorSpecific*/
#define RDM_OID_ZY_VENDOR_SPECIFIC               120948	/*Device.X_ZYXEL_Option125VendorSpecific.VendorSpecific.i*/
#define RDM_OID_ZY_IPP_CFG                       121080	/*Device.X_ZYXEL_Ipp_Cfg*/
#define RDM_OID_GPON                             121212	/*Device.X_ZYXEL_GPON*/
#define RDM_OID_ONU                              121248	/*Device.X_ZYXEL_GPON.ONU*/
#define RDM_OID_ANI                              121956	/*Device.X_ZYXEL_GPON.ANI*/
#define RDM_OID_OLT                              122424	/*Device.X_ZYXEL_GPON.OLT*/
#define RDM_OID_CAPABILITY                       122556	/*Device.X_ZYXEL_GPON.Capability*/
#define RDM_OID_LOIDAUTH                         122664	/*Device.X_ZYXEL_GPON.LOIDAuth*/
#define RDM_OID_SOFTIMAGE                        122772	/*Device.X_ZYXEL_GPON.SoftImage.i*/
#define RDM_OID_PM                               122904	/*Device.X_ZYXEL_GPON.PM*/
#define RDM_OID_COMMON                           123060	/*Device.X_ZYXEL_GPON.Common*/
#define RDM_OID_XPON                             123144	/*Device.X_ZYXEL_GPON.Xpon*/
#define RDM_OID_LINKCFG                          123300	/*Device.X_ZYXEL_GPON.LinkCfg*/
#define RDM_OID_IPHOST                           123384	/*Device.X_ZYXEL_GPON.IPHost*/
#define RDM_OID_OMCI_CFG                         123468	/*Device.X_ZYXEL_GPON.OmciConfig*/
#define RDM_OID_OMCI                             123504	/*Device.X_ZYXEL_GPON.OmciConfig.Omci*/
#define RDM_OID_GEMPORT                          123708	/*Device.X_ZYXEL_GPON.OmciConfig.GEMPort*/
#define RDM_OID_TCONT                            123864	/*Device.X_ZYXEL_GPON.OmciConfig.TCONT*/
#define RDM_OID_TRTCM                            123948	/*Device.X_ZYXEL_GPON.OmciConfig.Trtcm*/
#define RDM_OID_QOSCFG                           124104	/*Device.X_ZYXEL_GPON.OmciConfig.QosCfg*/
#define RDM_OID_QOS_VALUE                        124284	/*Device.X_ZYXEL_GPON.OmciConfig.QosCfg.QOSValue.i*/
#define RDM_OID_CNGSTCFG                         124344	/*Device.X_ZYXEL_GPON.OmciConfig.CngstCfg*/
#define RDM_OID_CONGEST_THRED_VALUE              124572	/*Device.X_ZYXEL_GPON.OmciConfig.CngstCfg.CongestThredValue.i*/
#define RDM_OID_TRTCMCFG                         124632	/*Device.X_ZYXEL_GPON.OmciConfig.TrtcmCfg*/
#define RDM_OID_TRTCM_VALUE                      124764	/*Device.X_ZYXEL_GPON.OmciConfig.TrtcmCfg.TrtcmValue.i*/
#define RDM_OID_QUEUE                            124824	/*Device.X_ZYXEL_GPON.OmciConfig.Queue*/
#define RDM_OID_ONT_GENERIC                      124884	/*Device.X_ZYXEL_GPON.OntGeneric*/
#define RDM_OID_ZY_ONE_CONNECT                   124944	/*Device.X_ZYXEL_OneConnect*/
#define RDM_OID_ONE_CONNECT_INTERNET_ACCESS_MASTER_SWITCH 125028	/*Device.X_ZYXEL_OneConnect_Internet_Access_Filter*/
#define RDM_OID_ONE_CONNECT_INTERNET_ACCESS_RULE 125112	/*Device.X_ZYXEL_OneConnect_Internet_Access_Filter.Rule.i*/
#define RDM_OID_ONE_CONNECT_P_C_GENERAL          125220	/*Device.X_ZYXEL_OneConnect_Parental_Control*/
#define RDM_OID_ONE_CONNECT_P_C_RULE             125304	/*Device.X_ZYXEL_OneConnect_Parental_Control.Rule.i*/
#define RDM_OID_ONLINE_F_W_UPGRADE               125532	/*Device.X_ZYXEL_Online_FW_Upgrade*/
#define RDM_OID_LANDING_PAGE                     125784	/*Device.X_ZYXEL_Landing_Page*/
#define RDM_OID_POWER_MGMT                       125868	/*Device.X_ZYXEL_Power_Management*/
#define RDM_OID_POWER_SCHEDULE                   126264	/*Device.X_ZYXEL_Power_Management.PowerSchedule.i*/
#define RDM_OID_ZY_LOOP_GUARD                    126420	/*Device.X_ZYXEL_LOOP_GUARD*/
#define RDM_OID_ZY_PROXIMITY_SENSOR              126528	/*Device.X_ZYXEL_PROXIMITY_SENSOR*/
#define RDM_OID_ZY_RESET_ADMIN                   126588	/*Device.X_ZYXEL_RESET_ADMIN*/
#define RDM_OID_OI_WIZARD                        126648	/*Device.X_ZYXEL_OiWizard*/

#define RDM_OID_MAX                   126852     // for OID validation

#define RDM_OID_IS_INVALID(_oid_)    ((_oid_ < 0) || (_oid_ >= RDM_OID_MAX))

#endif // _ZCFG_RDM_OID_H
