#ifndef _ZCFG_RDM_OID_H
#define _ZCFG_RDM_OID_H

#define RDM_OID_DEVICE                           0 	/*Device*/
#define RDM_OID_SERVICE                          108	/*Device.Services*/
#define RDM_OID_PACKAGE                          144	/*Device.Services.X_ZYXEL_Package.i*/
#define RDM_OID_PACKAGE_INSTALL                  372	/*Device.Services.X_ZYXEL_Package_Install*/
#define RDM_OID_VOICE_SRV                        456	/*Device.Services.VoiceService.i*/
#define RDM_OID_VOICE_CAPB                       540	/*Device.Services.VoiceService.i.Capabilities*/
#define RDM_OID_VOICE_CAPB_SIP                   1344	/*Device.Services.VoiceService.i.Capabilities.SIP*/
#define RDM_OID_VOICE_CAPB_MGCP                  1644	/*Device.Services.VoiceService.i.Capabilities.MGCP*/
#define RDM_OID_VOICE_CAPB_H323                  1704	/*Device.Services.VoiceService.i.Capabilities.H323*/
#define RDM_OID_VOICE_CAPB_CODEC                 1788	/*Device.Services.VoiceService.i.Capabilities.Codec.i*/
#define RDM_OID_VOICE_PROF                       1968	/*Device.Services.VoiceService.i.VoiceProfile.i*/
#define RDM_OID_VOICE_PROF_SRV_PRO_INFO          3012	/*Device.Services.VoiceService.i.VoiceProfile.i.ServiceProviderInfo*/
#define RDM_OID_VOICE_PROF_SIP                   3144	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP*/
#define RDM_OID_VOICE_PROF_SIP_SUBSCRIBE_OBJ     4788	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP.EventSubscribe.i*/
#define RDM_OID_VOICE_PROF_SIP_RESP_MAP_OBJ      4944	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP.ResponseMap.i*/
#define RDM_OID_VOICE_PROF_RTP                   5052	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP*/
#define RDM_OID_VOICE_PROF_RTP_RTCP              5232	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.RTCP*/
#define RDM_OID_VOICE_PROF_RTP_SRTP              5340	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.SRTP*/
#define RDM_OID_VOICE_PROF_RTP_REDUNDANCY        5472	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.Redundancy*/
#define RDM_OID_VOICE_PROF_NUM_PLAN              5700	/*Device.Services.VoiceService.i.VoiceProfile.i.NumberingPlan*/
#define RDM_OID_VOICE_PROF_NUM_PLAN_PREFIX_INFO  5952	/*Device.Services.VoiceService.i.VoiceProfile.i.NumberingPlan.PrefixInfo.i*/
#define RDM_OID_VOICE_PROF_TONE                  6180	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone*/
#define RDM_OID_VOICE_PROF_TONE_EVENT            6288	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Event.i*/
#define RDM_OID_VOICE_PROF_TONE_DESCRIPTION      6372	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Description.i*/
#define RDM_OID_VOICE_PROF_TONE_PATTERN          6576	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Pattern.i*/
#define RDM_OID_VOICE_PROF_FAX_T38               6948	/*Device.Services.VoiceService.i.VoiceProfile.i.FaxT38*/
#define RDM_OID_VOICE_LINE                       7128	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i*/
#define RDM_OID_VOICE_LINE_SIP                   7500	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.SIP*/
#define RDM_OID_VOICE_LINE_SIP_EVENT_SUBS        7776	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.SIP.EventSubscribe.i*/
#define RDM_OID_VOICE_LINE_RINGER                7884	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer*/
#define RDM_OID_VOICE_LINE_RINGER_EVENT          7992	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Event.i*/
#define RDM_OID_VOICE_LINE_RINGER_DESCRIPTION    8076	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Description.i*/
#define RDM_OID_VOICE_LINE_RINGER_PATTERN        8232	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Pattern.i*/
#define RDM_OID_VOICE_LINE_CALLING_FEATURE       8364	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.CallingFeatures*/
#define RDM_OID_VOICE_LINE_PROCESSING            9864	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.VoiceProcessing*/
#define RDM_OID_VOICE_LINE_CODEC                 10020	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Codec*/
#define RDM_OID_VOICE_LINE_CODEC_LIST            10224	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Codec.List.i*/
#define RDM_OID_VOICE_LINE_SESSION               10500	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Session.i*/
#define RDM_OID_VOICE_LINE_STATS                 10656	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Stats*/
#define RDM_OID_VOICE_PHY_INTF                   11436	/*Device.Services.VoiceService.i.PhyInterface.i*/
#define RDM_OID_VOICE_PSTN                       12096	/*Device.Services.VoiceService.i.X_ZYXEL_PSTN.i*/
#define RDM_OID_VOICE_COMMON                     12276	/*Device.Services.VoiceService.i.X_ZYXEL_Common*/
#define RDM_OID_VOICE_PHONE_BOOK                 12816	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook*/
#define RDM_OID_SPEED_DIAL_BOOK                  12852	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.SpeedDialBook*/
#define RDM_OID_SPEED_DIAL_BOOK_LIST             12912	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.SpeedDialBook.List.i*/
#define RDM_OID_CALL_POLICY_BOOK                 13092	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.CallPolicyBook*/
#define RDM_OID_CALL_POLICY_BOOK_LIST            13176	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.CallPolicyBook.List.i*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK 13356	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK_IF_LIST 13416	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook.InterfaceList.i*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK_PORT_LIST 13500	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook.InterfaceList.i.PortList.i*/
#define RDM_OID_VOICE_FXO                        13560	/*Device.Services.VoiceService.i.X_ZYXEL_FXO*/
#define RDM_OID_VOICE_FXO_PORT                   13620	/*Device.Services.VoiceService.i.X_ZYXEL_FXO.Port.i*/
#define RDM_OID_VOICE_DECT                       13896	/*Device.Services.VoiceService.i.X_ZYXEL_DECT*/
#define RDM_OID_VOICE_DECT_B_S                   13956	/*Device.Services.VoiceService.i.X_ZYXEL_DECT.BaseStation*/
#define RDM_OID_VOICE_DECT_H_S                   14448	/*Device.Services.VoiceService.i.X_ZYXEL_DECT.Handset.i*/
#define RDM_OID_VOICE_CALL_STATUS                14772	/*Device.Services.VoiceService.i.X_ZYXEL_CALL_STATUS*/
#define RDM_OID_DEV_INFO                         15000	/*Device.DeviceInfo*/
#define RDM_OID_DEV_INFO_VEND_CONF_FILE          15588	/*Device.DeviceInfo.VendorConfigFile.i*/
#define RDM_OID_DEV_INFO_SUP_DATA_MODEL          15744	/*Device.DeviceInfo.SupportedDataModel.i*/
#define RDM_OID_DEV_INFO_MEM_STAT                15876	/*Device.DeviceInfo.MemoryStatus*/
#define RDM_OID_DEV_INFO_PS_STAT                 15960	/*Device.DeviceInfo.ProcessStatus*/
#define RDM_OID_DEV_INFO_PS_STAT_PS              16044	/*Device.DeviceInfo.ProcessStatus.Process.i*/
#define RDM_OID_TEMP_STAT                        16224	/*Device.DeviceInfo.TemperatureStatus*/
#define RDM_OID_TEMP_STAT_TEMP_SENSOR            16284	/*Device.DeviceInfo.TemperatureStatus.TemperatureSensor.i*/
#define RDM_OID_NETWORK_PROP                     16728	/*Device.DeviceInfo.NetworkProperties.i*/
#define RDM_OID_DEV_INFO_PROCESSOR               16812	/*Device.DeviceInfo.Processor.i*/
#define RDM_OID_DEV_INFO_VENDOR_LOG_FILE         16896	/*Device.DeviceInfo.VendorLogFile.i*/
#define RDM_OID_DEV_INFO_PROXIER_INFO            17028	/*Device.DeviceInfo.ProxierInfo.i*/
#define RDM_OID_DEV_INFO_LOC                     17160	/*Device.DeviceInfo.Location.i*/
#define RDM_OID_DEV_INFO_POWER_STAT              17316	/*Device.DeviceInfo.X_ZYXEL_PowerStatus*/
#define RDM_OID_MGMT_SRV                         17400	/*Device.ManagementServer*/
#define RDM_OID_MGMT_SRV_MGAB_DEV                19524	/*Device.ManagementServer.ManageableDevice.i*/
#define RDM_OID_MGMT_SRV_AUTO_TRANS_COMPLETE_POL 19704	/*Device.ManagementServer.AutonomousTransferCompletePolicy*/
#define RDM_OID_MGMT_SRV_DL_AVAIL                19836	/*Device.ManagementServer.DownloadAvailability*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_ANNCMNT        19872	/*Device.ManagementServer.DownloadAvailability.Announcement*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_ANNCMNT_GROUP  19980	/*Device.ManagementServer.DownloadAvailability.Announcement.Group.i*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_QUERY          20112	/*Device.ManagementServer.DownloadAvailability.Query*/
#define RDM_OID_MGMT_SRV_DU_STATE_CHANGE_COMPL_POL 20220	/*Device.ManagementServer.DUStateChangeComplPolicy*/
#define RDM_OID_MGMT_SRV_EMBEDED_DEV             20352	/*Device.ManagementServer.EmbeddedDevice.i*/
#define RDM_OID_MGMT_SRV_VIRTUAL_DEV             20604	/*Device.ManagementServer.VirtualDevice.i*/
#define RDM_OID_MGMT_SRV_INFORM_PAR              20760	/*Device.ManagementServer.InformParameter.i*/
#define RDM_OID_GATEWAY_INFO                     20892	/*Device.GatewayInfo*/
#define RDM_OID_TIME                             21000	/*Device.Time*/
#define RDM_OID_USR_INTF                         21660	/*Device.UserInterface*/
#define RDM_OID_USR_INTF_REMO_ACESS              22272	/*Device.UserInterface.RemoteAccess*/
#define RDM_OID_USR_INTF_LOCAL_DISP              22404	/*Device.UserInterface.LocalDisplay*/
#define RDM_OID_IFACE_STACK                      22632	/*Device.InterfaceStack.i*/
#define RDM_OID_DSL                              22788	/*Device.DSL*/
#define RDM_OID_DSL_LINE                         22920	/*Device.DSL.Line.i*/
#define RDM_OID_DSL_LINE_ST                      27108	/*Device.DSL.Line.i.Stats*/
#define RDM_OID_DSL_LINE_ST_TOTAL                27480	/*Device.DSL.Line.i.Stats.Total*/
#define RDM_OID_DSL_LINE_ST_SHOWTIME             28212	/*Device.DSL.Line.i.Stats.Showtime*/
#define RDM_OID_DSL_LINE_ST_LAST_SHOWTIME        28752	/*Device.DSL.Line.i.Stats.LastShowtime*/
#define RDM_OID_DSL_LINE_ST_LAST_CUR_DAY         28836	/*Device.DSL.Line.i.Stats.CurrentDay*/
#define RDM_OID_DSL_LINE_ST_LAST_QUAR_HR         29328	/*Device.DSL.Line.i.Stats.QuarterHour*/
#define RDM_OID_DSL_LINE_TEST_PARAMS             29412	/*Device.DSL.Line.i.TestParams*/
#define RDM_OID_DSL_CHANNEL                      29976	/*Device.DSL.Channel.i*/
#define RDM_OID_DSL_CHANNEL_ST                   30492	/*Device.DSL.Channel.i.Stats*/
#define RDM_OID_DSL_CHANNEL_ST_TOTAL             30840	/*Device.DSL.Channel.i.Stats.Total*/
#define RDM_OID_DSL_CHANNEL_ST_SHOWTIME          31020	/*Device.DSL.Channel.i.Stats.Showtime*/
#define RDM_OID_DSL_CHANNEL_ST_LAST_SHOWTIME     31200	/*Device.DSL.Channel.i.Stats.LastShowtime*/
#define RDM_OID_DSL_CHANNEL_ST_CUR_DAY           31380	/*Device.DSL.Channel.i.Stats.CurrentDay*/
#define RDM_OID_DSL_CHANNEL_ST_QUAR_HR           31560	/*Device.DSL.Channel.i.Stats.QuarterHour*/
#define RDM_OID_DSL_BOND_GP                      31740	/*Device.DSL.BondingGroup.i*/
#define RDM_OID_DSL_BOND_GP_BONDED_CHANNEL       32256	/*Device.DSL.BondingGroup.i.BondedChannel.i*/
#define RDM_OID_DSL_BOND_GP_BONDED_CHANNEL_ETH   32340	/*Device.DSL.BondingGroup.i.BondedChannel.i.Ethernet*/
#define RDM_OID_DSL_BOND_GP_BONDED_CHANNEL_ETH_ST 32376	/*Device.DSL.BondingGroup.i.BondedChannel.i.Ethernet.Stats*/
#define RDM_OID_DSL_BOND_GP_ST                   32604	/*Device.DSL.BondingGroup.i.Stats*/
#define RDM_OID_DSL_BOND_GP_ST_TOTAL             33072	/*Device.DSL.BondingGroup.i.Stats.Total*/
#define RDM_OID_DSL_BOND_GP_ST_CURRENT_DAY       33372	/*Device.DSL.BondingGroup.i.Stats.CurrentDay*/
#define RDM_OID_DSL_BOND_GP_ST_QTR_HR            33672	/*Device.DSL.BondingGroup.i.Stats.QuarterHour*/
#define RDM_OID_DSL_BOND_GP_ETH                  33972	/*Device.DSL.BondingGroup.i.Ethernet*/
#define RDM_OID_DSL_BOND_GP_ETH_ST               34008	/*Device.DSL.BondingGroup.i.Ethernet.Stats*/
#define RDM_OID_DSL_DIAG                         34428	/*Device.DSL.Diagnostics*/
#define RDM_OID_DSL_DIAG_ADSL_LINE_TEST          34464	/*Device.DSL.Diagnostics.ADSLLineTest*/
#define RDM_OID_OPT                              35364	/*Device.Optical*/
#define RDM_OID_OPT_INTF                         35424	/*Device.Optical.Interface.i*/
#define RDM_OID_OPT_INTF_ST                      35772	/*Device.Optical.Interface.i.Stats*/
#define RDM_OID_ATM                              36000	/*Device.ATM*/
#define RDM_OID_ATM_LINK                         36060	/*Device.ATM.Link.i*/
#define RDM_OID_ATM_LINK_ST                      36600	/*Device.ATM.Link.i.Stats*/
#define RDM_OID_ATM_LINK_QOS                     37212	/*Device.ATM.Link.i.QoS*/
#define RDM_OID_ATM_DIAG                         37368	/*Device.ATM.Diagnostics*/
#define RDM_OID_ATM_DIAG_F5_LO                   37404	/*Device.ATM.Diagnostics.F5Loopback*/
#define RDM_OID_ATM_DIAG_F4_LO                   37704	/*Device.ATM.Diagnostics.X_ZYXEL_F4Loopback*/
#define RDM_OID_PTM                              38004	/*Device.PTM*/
#define RDM_OID_PTM_LINK                         38064	/*Device.PTM.Link.i*/
#define RDM_OID_PTM_LINK_ST                      38628	/*Device.PTM.Link.i.Stats*/
#define RDM_OID_ETH                              39144	/*Device.Ethernet*/
#define RDM_OID_ETH_RMON_ST                      39276	/*Device.Ethernet.RMONStats.i*/
#define RDM_OID_ETH_IFACE                        39840	/*Device.Ethernet.Interface.i*/
#define RDM_OID_ETH_INTF_ST                      40404	/*Device.Ethernet.Interface.i.Stats*/
#define RDM_OID_ETH_LINK                         40800	/*Device.Ethernet.Link.i*/
#define RDM_OID_ETH_LINK_ST                      41124	/*Device.Ethernet.Link.i.Stats*/
#define RDM_OID_ETH_VLAN_TERM                    41520	/*Device.Ethernet.VLANTermination.i*/
#define RDM_OID_ETH_VLAN_TERM_ST                 41820	/*Device.Ethernet.VLANTermination.i.Stats*/
#define RDM_OID_USB                              42216	/*Device.USB*/
#define RDM_OID_USB_INTF                         42300	/*Device.USB.Interface.i*/
#define RDM_OID_USB_INTF_STAT                    42600	/*Device.USB.Interface.i.Stats*/
#define RDM_OID_USB_PORT                         42996	/*Device.USB.Port.i*/
#define RDM_OID_USB_USBHOSTS                     43224	/*Device.USB.USBHosts*/
#define RDM_OID_USB_USBHOSTS_HOST                43284	/*Device.USB.USBHosts.Host.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV            43512	/*Device.USB.USBHosts.Host.i.Device.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_PAR        44028	/*Device.USB.USBHosts.Host.i.Device.i.X_ZYXEL_Partition.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_CFG        44184	/*Device.USB.USBHosts.Host.i.Device.i.Configuration.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_CFG_INTF   44268	/*Device.USB.USBHosts.Host.i.Device.i.Configuration.i.Interface.i*/
#define RDM_OID_CELLULAR                         44400	/*Device.Cellular*/
#define RDM_OID_CELLULAR_INTERFACE               44508	/*Device.Cellular.Interface.i*/
#define RDM_OID_CELLULAR_IFACE_U_S_I_M           44856	/*Device.Cellular.Interface.i.USIM*/
#define RDM_OID_CELLULAR_ACCESS_POINT            44964	/*Device.Cellular.AccessPoint.i*/
#define RDM_OID_HPNA                             45192	/*Device.HPNA*/
#define RDM_OID_HPNA_INTF                        45252	/*Device.HPNA.Interface.i*/
#define RDM_OID_HPNA_INTF_ST                     45936	/*Device.HPNA.Interface.i.Stats*/
#define RDM_OID_HPNA_INTF_QOS                    46332	/*Device.HPNA.Interface.i.QoS*/
#define RDM_OID_HPNA_INTF_QOS_FLOW_SPEC          46392	/*Device.HPNA.Interface.i.QoS.FlowSpec.i*/
#define RDM_OID_HPNA_INTF_ASSOC_DEV              46764	/*Device.HPNA.Interface.i.AssociatedDevice.i*/
#define RDM_OID_HPNA_DIAG                        46992	/*Device.HPNA.Diagnostics*/
#define RDM_OID_HPNA_DIAG_PHY_THROUGHPUT         47028	/*Device.HPNA.Diagnostics.PHYThroughput*/
#define RDM_OID_HPNA_DIAG_PHY_THROUGHPUT_RESULT  47304	/*Device.HPNA.Diagnostics.PHYThroughput.Result.i*/
#define RDM_OID_HPNA_DIAG_PERF_MONT              47508	/*Device.HPNA.Diagnostics.PerformanceMonitoring*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_NODES     47616	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Nodes*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_NODES_NODE 47724	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Nodes.Node.i*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_CHANNELS  48360	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Channels*/
#define RDM_OID_HPNA_DIAG_PERF_MONITOR_CHANNELS_CHANNEL 48444	/*Device.HPNA.Diagnostics.PerformanceMonitoring.Channels.Channel.i*/
#define RDM_OID_MOCA                             48744	/*Device.MoCA*/
#define RDM_OID_MOCA_INTF                        48804	/*Device.MoCA.Interface.i*/
#define RDM_OID_MOCA_INTF_ST                     49704	/*Device.MoCA.Interface.i.Stats*/
#define RDM_OID_MOCA_INTF_QOS                    50100	/*Device.MoCA.Interface.i.QoS*/
#define RDM_OID_MOCA_INTF_QOS_FLOW_ST            50208	/*Device.MoCA.Interface.i.QoS.FlowStats.i*/
#define RDM_OID_MOCA_INTF_ASSOC_DEV              50388	/*Device.MoCA.Interface.i.AssociatedDevice.i*/
#define RDM_OID_GHN                              50832	/*Device.Ghn*/
#define RDM_OID_GHN_INTF                         50892	/*Device.Ghn.Interface.i*/
#define RDM_OID_GHN_INTF_ST                      51456	/*Device.Ghn.Interface.i.Stats*/
#define RDM_OID_GHN_INTF_ASSOC_DEV               51852	/*Device.Ghn.Interface.i.AssociatedDevice.i*/
#define RDM_OID_HOME_PLUG                        52008	/*Device.Homeplug*/
#define RDM_OID_HOMEPLUG_INTF                    52068	/*Device.Homeplug.Interface.i*/
#define RDM_OID_HOMEPLUG_INTF_ST                 52488	/*Device.Homeplug.Interface.i.Stats*/
#define RDM_OID_HOMEPLUG_INTF_ASSOC_DEV          53004	/*Device.Homeplug.Interface.i.AssociatedDevice.i*/
#define RDM_OID_UPA                              53208	/*Device.UPA*/
#define RDM_OID_UPA_INTF                         53268	/*Device.UPA.Interface.i*/
#define RDM_OID_UPA_INTF_ST                      53808	/*Device.UPA.Interface.i.Stats*/
#define RDM_OID_UPA_INTF_ASSOC_DEV               54204	/*Device.UPA.Interface.i.AssociatedDevice.i*/
#define RDM_OID_UPA_INTF_ACTIVE_NOTCH            54504	/*Device.UPA.Interface.i.ActiveNotch.i*/
#define RDM_OID_UPA_INTF_BRIDGE_FOR              54660	/*Device.UPA.Interface.i.BridgeFor.i*/
#define RDM_OID_UPA_DIAG                         54768	/*Device.UPA.Diagnostics*/
#define RDM_OID_UPA_DIAG_INTF_MEASUREMENT        54804	/*Device.UPA.Diagnostics.InterfaceMeasurement*/
#define RDM_OID_WIFI                             54984	/*Device.WiFi*/
#define RDM_OID_WIFI_ONE_SSID                    55188	/*Device.WiFi.X_ZYXEL_OneSSID*/
#define RDM_OID_WIFI_RADIO                       55248	/*Device.WiFi.Radio.i*/
#define RDM_OID_WIFI_RADIO_ST                    57036	/*Device.WiFi.Radio.i.Stats*/
#define RDM_OID_WIFI_SSID                        57288	/*Device.WiFi.SSID.i*/
#define RDM_OID_WIFI_SSID_STAT                   58020	/*Device.WiFi.SSID.i.Stats*/
#define RDM_OID_WIFI_ACCESS_POINT                58440	/*Device.WiFi.AccessPoint.i*/
#define RDM_OID_WIFI_ACCESS_POINT_SEC            58812	/*Device.WiFi.AccessPoint.i.Security*/
#define RDM_OID_WIFI_ACCESS_POINT_ACCOUNTING     59928	/*Device.WiFi.AccessPoint.i.Accounting*/
#define RDM_OID_WIFI_ACCESS_POINT_WPS            60156	/*Device.WiFi.AccessPoint.i.WPS*/
#define RDM_OID_WIFI_ACCESS_POINT_ASSOC_DEV      60624	/*Device.WiFi.AccessPoint.i.AssociatedDevice.i*/
#define RDM_OID_WIFI_ACCESS_POINT_ASSOC_DEV_ST   60900	/*Device.WiFi.AccessPoint.i.AssociatedDevice.i.Stats*/
#define RDM_OID_WIFI_STA_FILTER                  61152	/*Device.WiFi.AccessPoint.i.StationFilter*/
#define RDM_OID_WIFI_END_POINT                   61236	/*Device.WiFi.EndPoint.i*/
#define RDM_OID_WIFI_END_POINT_ST                61416	/*Device.WiFi.EndPoint.i.Stats*/
#define RDM_OID_WIFI_END_POINT_SEC               61548	/*Device.WiFi.EndPoint.i.Security*/
#define RDM_OID_WIFI_END_POINT_PROFILE           61608	/*Device.WiFi.EndPoint.i.Profile.i*/
#define RDM_OID_WIFI_END_POINT_PROFILE_SEC       61788	/*Device.WiFi.EndPoint.i.Profile.i.Security*/
#define RDM_OID_WIFI_END_POINT_WPS               61944	/*Device.WiFi.EndPoint.i.WPS*/
#define RDM_OID_WIFI_DIAGNOSTIC                  62388	/*Device.WiFi.NeighboringWiFiDiagnostic*/
#define RDM_OID_WIFI_DIAGNOSTIC_RESULTS          62496	/*Device.WiFi.NeighboringWiFiDiagnostic.Result.i*/
#define RDM_OID_WIFI_AP_STEERING                 62940	/*Device.WiFi.X_ZYXEL_ApSteering*/
#define RDM_OID_WLAN_SCHEDULER                   63384	/*Device.WiFi.X_ZYXEL_WLAN_Scheduler.i*/
#define RDM_OID_WIFI_MAP                         63708	/*Device.WiFi.MultiAP*/
#define RDM_OID_WIFI_MAP_STEERING_SUM_ST         63768	/*Device.WiFi.MultiAP.SteeringSummaryStats*/
#define RDM_OID_WIFI_MAP_APDEV                   63996	/*Device.WiFi.MultiAP.APDevice.i*/
#define RDM_OID_WIFI_MAP_APDEV_RADIO             64392	/*Device.WiFi.MultiAP.APDevice.i.Radio.i*/
#define RDM_OID_WIFI_MAP_APDEV_RADIO_AP          64644	/*Device.WiFi.MultiAP.APDevice.i.Radio.i.AP.i*/
#define RDM_OID_WIFI_MAP_APDEV_RADIO_AP_ASSOCDEV 64824	/*Device.WiFi.MultiAP.APDevice.i.Radio.i.AP.i.AssociatedDevice.i*/
#define RDM_OID_WIFI_MAP_APDEV_RADIO_AP_ASSOCDEV_ST 65076	/*Device.WiFi.MultiAP.APDevice.i.Radio.i.AP.i.AssociatedDevice.i.Stats*/
#define RDM_OID_WIFI_MAP_APDEV_RADIO_AP_ASSOCDEV_STEERING_SUM_ST 65280	/*Device.WiFi.MultiAP.APDevice.i.Radio.i.AP.i.AssociatedDevice.i.SteeringSummaryStats*/
#define RDM_OID_WIFI_MAP_APDEV_RADIO_AP_ASSOCDEV_STEERING_HISTORY 65532	/*Device.WiFi.MultiAP.APDevice.i.Radio.i.AP.i.AssociatedDevice.i.SteeringHistory.i*/
#define RDM_OID_BRIDGING                         65712	/*Device.Bridging*/
#define RDM_OID_BRIDGING_BR                      65988	/*Device.Bridging.Bridge.i*/
#define RDM_OID_BRIDGING_BR_PORT                 66312	/*Device.Bridging.Bridge.i.Port.i*/
#define RDM_OID_BRIDGING_BR_PORT_ST              66804	/*Device.Bridging.Bridge.i.Port.i.Stats*/
#define RDM_OID_BRIDGING_BR_VLAN                 67200	/*Device.Bridging.Bridge.i.VLAN.i*/
#define RDM_OID_BRIDGING_BR_VLANPORT             67332	/*Device.Bridging.Bridge.i.VLANPort.i*/
#define RDM_OID_BRIDGING_FILTER                  67488	/*Device.Bridging.Filter.i*/
#define RDM_OID_PPP                              68316	/*Device.PPP*/
#define RDM_OID_PPP_IFACE                        68400	/*Device.PPP.Interface.i*/
#define RDM_OID_PPP_IFACE_PPPOA                  69348	/*Device.PPP.Interface.i.PPPoA*/
#define RDM_OID_PPP_IFACE_PPPOE                  69384	/*Device.PPP.Interface.i.PPPoE*/
#define RDM_OID_PPP_IFACE_IPCP                   69516	/*Device.PPP.Interface.i.IPCP*/
#define RDM_OID_PPP_INTF_IPV6CP                  69672	/*Device.PPP.Interface.i.IPV6CP*/
#define RDM_OID_PPP_IFACE_STAT                   69756	/*Device.PPP.Interface.i.Stats*/
#define RDM_OID_IP                               70152	/*Device.IP*/
#define RDM_OID_IP_IFACE                         70404	/*Device.IP.Interface.i*/
#define RDM_OID_IP_IFACE_V4_ADDR                 71952	/*Device.IP.Interface.i.IPv4Address.i*/
#define RDM_OID_IP_IFACE_V6_ADDR                 72204	/*Device.IP.Interface.i.IPv6Address.i*/
#define RDM_OID_IP_IFACE_V6_PREFIX               72576	/*Device.IP.Interface.i.IPv6Prefix.i*/
#define RDM_OID_IP_IFACE_STAT                    73020	/*Device.IP.Interface.i.Stats*/
#define RDM_OID_IP_ACTIVE_PORT                   73416	/*Device.IP.ActivePort.i*/
#define RDM_OID_IP_DIAG                          73572	/*Device.IP.Diagnostics*/
#define RDM_OID_IP_DIAG_IPPING                   73608	/*Device.IP.Diagnostics.IPPing*/
#define RDM_OID_IP_DIAG_TRACE_RT                 74052	/*Device.IP.Diagnostics.TraceRoute*/
#define RDM_OID_IP_DIAG_TRACERT_RT_HOPS          74376	/*Device.IP.Diagnostics.TraceRoute.RouteHops.i*/
#define RDM_OID_IP_DIAG_DL_DIAG                  74508	/*Device.IP.Diagnostics.DownloadDiagnostics*/
#define RDM_OID_IP_DIAG_UL_DIAG                  75000	/*Device.IP.Diagnostics.UploadDiagnostics*/
#define RDM_OID_IP_DIAG_UDP_ECHO_CFG             75444	/*Device.IP.Diagnostics.UDPEchoConfig*/
#define RDM_OID_IP_DIAG_UDP_ECHO_DIAG            75768	/*Device.IP.Diagnostics.UDPEchoDiagnostics*/
#define RDM_OID_IP_DIAG_UDP_ECHO_PAK_RST         76284	/*Device.IP.Diagnostics.UDPEchoDiagnostics.IndividualPacketResult.i*/
#define RDM_OID_IP_DIAG_SVR_SELECT_DIAG          76512	/*Device.IP.Diagnostics.ServerSelectionDiagnostics*/
#define RDM_OID_IPSEC                            76836	/*Device.IPsec*/
#define RDM_OID_IPSEC_STAT                       77328	/*Device.IPsec.Stats*/
#define RDM_OID_IPSEC_FILTER                     77652	/*Device.IPsec.Filter.i*/
#define RDM_OID_IPSEC_PROFILE                    78648	/*Device.IPsec.Profile.i*/
#define RDM_OID_IPSEC_PROFILE_SENT_CP_ATTR       80436	/*Device.IPsec.Profile.i.SentCPAttr.i*/
#define RDM_OID_IPSEC_TUNNEL                     80568	/*Device.IPsec.Tunnel.i*/
#define RDM_OID_IPSEC_TUNNEL_STAT                81300	/*Device.IPsec.Tunnel.i.Stats*/
#define RDM_OID_IPSEC_IKEV2SA                    81456	/*Device.IPsec.IKEv2SA.i*/
#define RDM_OID_IPSEC_IKEV2SA_STAT               81804	/*Device.IPsec.IKEv2SA.i.Stats*/
#define RDM_OID_IPSEC_IKEV2SA_RECEIVED_CP_ATTR   82032	/*Device.IPsec.IKEv2SA.i.ReceivedCPAttr.i*/
#define RDM_OID_IPSEC_IKEV2SA_CHILD_SA           82116	/*Device.IPsec.IKEv2SA.i.ChildSA.i*/
#define RDM_OID_IPSEC_IKEV2SA_CHILD_SA_STAT      82272	/*Device.IPsec.IKEv2SA.i.ChildSA.i.Stats*/
#define RDM_OID_ZY_IPSEC_XML_RELOAD              82548	/*Device.IPsec.X_ZYXEL_XML_Reload*/
#define RDM_OID_GRE                              82608	/*Device.GRE*/
#define RDM_OID_GRE_TUNNEL                       82692	/*Device.GRE.Tunnel.i*/
#define RDM_OID_GRE_TUNNEL_STAT                  83208	/*Device.GRE.Tunnel.i.Stats*/
#define RDM_OID_GRE_TUNNEL_IFACE                 83484	/*Device.GRE.Tunnel.i.Interface.i*/
#define RDM_OID_GRE_TUNNEL_IFACE_STAT            83784	/*Device.GRE.Tunnel.i.Interface.i.Stats*/
#define RDM_OID_GRE_FILTER                       84012	/*Device.GRE.Filter.i*/
#define RDM_OID_MAP                              84264	/*Device.MAP*/
#define RDM_OID_MAP_DOMAIN                       84348	/*Device.MAP.Domain.i*/
#define RDM_OID_MAP_DOMAIN_RULE                  84720	/*Device.MAP.Domain.i.Rule.i*/
#define RDM_OID_MAP_DOMAIN_IFACE                 85020	/*Device.MAP.Domain.i.Interface*/
#define RDM_OID_MAP_DOMAIN_IFACE_STAT            85200	/*Device.MAP.Domain.i.Interface.Stats*/
#define RDM_OID_CAPT_PORTAL                      85596	/*Device.CaptivePortal*/
#define RDM_OID_ROUTING                          85728	/*Device.Routing*/
#define RDM_OID_ROUTING_ROUTER                   85788	/*Device.Routing.Router.i*/
#define RDM_OID_ROUTING_ROUTER_V4_FWD            86016	/*Device.Routing.Router.i.IPv4Forwarding.i*/
#define RDM_OID_ROUTING_ROUTER_V6_FWD            86532	/*Device.Routing.Router.i.IPv6Forwarding.i*/
#define RDM_OID_ROUTING_RIP                      86808	/*Device.Routing.RIP*/
#define RDM_OID_ROUTING_RIP_INTF_SET             86916	/*Device.Routing.RIP.InterfaceSetting.i*/
#define RDM_OID_ROUTING_RT_INFO                  87168	/*Device.Routing.RouteInformation*/
#define RDM_OID_ROUTING_RT_INFO_INTF_SET         87252	/*Device.Routing.RouteInformation.InterfaceSetting.i*/
#define RDM_OID_NEIGHBOR_DISCOVERY               87528	/*Device.NeighborDiscovery*/
#define RDM_OID_NEIGHBOR_DISCOVERY_INTF_SET      87612	/*Device.NeighborDiscovery.InterfaceSetting.i*/
#define RDM_OID_RT_ADV                           87912	/*Device.RouterAdvertisement*/
#define RDM_OID_RT_ADV_INTF_SET                  87996	/*Device.RouterAdvertisement.InterfaceSetting.i*/
#define RDM_OID_RT_ADV_INTF_SET_OPT              88584	/*Device.RouterAdvertisement.InterfaceSetting.i.Option.i*/
#define RDM_OID_IPV6RD                           88716	/*Device.IPv6rd*/
#define RDM_OID_IPV6RD_INTF                      88800	/*Device.IPv6rd.InterfaceSetting.i*/
#define RDM_OID_DS_LITE                          89100	/*Device.DSLite*/
#define RDM_OID_DS_LITE_INTF_SET                 89184	/*Device.DSLite.InterfaceSetting.i*/
#define RDM_OID_QOS                              89532	/*Device.QoS*/
#define RDM_OID_QOS_CLS                          90144	/*Device.QoS.Classification.i*/
#define RDM_OID_QOS_APP                          92268	/*Device.QoS.App.i*/
#define RDM_OID_QOS_FLOW                         92544	/*Device.QoS.Flow.i*/
#define RDM_OID_QOS_POLICER                      92868	/*Device.QoS.Policer.i*/
#define RDM_OID_QOS_QUE                          93432	/*Device.QoS.Queue.i*/
#define RDM_OID_QOS_QUE_STAT                     93972	/*Device.QoS.QueueStats.i*/
#define RDM_OID_QOS_SHAPER                       94272	/*Device.QoS.Shaper.i*/
#define RDM_OID_LAN_CONF_SEC                     94452	/*Device.LANConfigSecurity*/
#define RDM_OID_HOSTS                            94512	/*Device.Hosts*/
#define RDM_OID_HOSTS_HOST                       94596	/*Device.Hosts.Host.i*/
#define RDM_OID_HOSTS_HOST_V4_ADDR               95568	/*Device.Hosts.Host.i.IPv4Address.i*/
#define RDM_OID_HOSTS_HOST_V6_ADDR               95628	/*Device.Hosts.Host.i.IPv6Address.i*/
#define RDM_OID_ZY_HOSTS_HOST_EXT                95688	/*Device.Hosts.Host.i.X_ZYXEL_EXT*/
#define RDM_OID_DNS                              95988	/*Device.DNS*/
#define RDM_OID_DNS_CLIENT                       96144	/*Device.DNS.Client*/
#define RDM_OID_DNS_CLIENT_SRV                   96276	/*Device.DNS.Client.Server.i*/
#define RDM_OID_DNS_RELAY                        96552	/*Device.DNS.Relay*/
#define RDM_OID_DNS_RELAY_FWD                    96684	/*Device.DNS.Relay.Forwarding.i*/
#define RDM_OID_DNS_DIAG                         96864	/*Device.DNS.Diagnostics*/
#define RDM_OID_DNS_DIAG_NS_LOOKUP_DIAG          96900	/*Device.DNS.Diagnostics.NSLookupDiagnostics*/
#define RDM_OID_DNS_DIAG_NS_LOOKUP_DIAG_RESULT   97152	/*Device.DNS.Diagnostics.NSLookupDiagnostics.Result.i*/
#define RDM_OID_NAT                              97332	/*Device.NAT*/
#define RDM_OID_NAT_INTF_SETTING                 97608	/*Device.NAT.InterfaceSetting.i*/
#define RDM_OID_NAT_PORT_MAPPING                 97764	/*Device.NAT.PortMapping.i*/
#define RDM_OID_NAT_PORT_TRIGGERING              98280	/*Device.NAT.X_ZYXEL_PortTriggering.i*/
#define RDM_OID_NAT_ADDR_MAPPING                 98604	/*Device.NAT.X_ZYXEL_AddrMapping.i*/
#define RDM_OID_NAT_SESSION_CTL                  98928	/*Device.NAT.X_ZYXEL_SessionControl*/
#define RDM_OID_DHCPV4                           99132	/*Device.DHCPv4*/
#define RDM_OID_DHCPV4_CLIENT                    99192	/*Device.DHCPv4.Client.i*/
#define RDM_OID_DHCPV4_SENT_OPT                  99684	/*Device.DHCPv4.Client.i.SentOption.i*/
#define RDM_OID_DHCPV4_REQ_OPT                   99816	/*Device.DHCPv4.Client.i.ReqOption.i*/
#define RDM_OID_DHCPV4_SRV                       99972	/*Device.DHCPv4.Server*/
#define RDM_OID_DHCPV4_SRV_POOL                  100080	/*Device.DHCPv4.Server.Pool.i*/
#define RDM_OID_DHCPV4_SRV_POOL_STATIC_ADDR      100932	/*Device.DHCPv4.Server.Pool.i.StaticAddress.i*/
#define RDM_OID_DHCPV4_SRV_POOL_OPT              101064	/*Device.DHCPv4.Server.Pool.i.Option.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT           101196	/*Device.DHCPv4.Server.Pool.i.Client.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT_V4_ADDR   101352	/*Device.DHCPv4.Server.Pool.i.Client.i.IPv4Address.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT_OPT       101436	/*Device.DHCPv4.Server.Pool.i.Client.i.Option.i*/
#define RDM_OID_DHCPV4_SRV_SUBNET                101520	/*Device.DHCPv4.Server.X_ZYXEL_Subnet.i*/
#define RDM_OID_DHCPV4_RELAY                     101700	/*Device.DHCPv4.Relay*/
#define RDM_OID_DHCPV4_RELAY_FWD                 101808	/*Device.DHCPv4.Relay.Forwarding.i*/
#define RDM_OID_DHCPV6                           102252	/*Device.DHCPv6*/
#define RDM_OID_DHCPV6_CLIENT                    102312	/*Device.DHCPv6.Client.i*/
#define RDM_OID_DHCPV6_CLIENT_SRV                102780	/*Device.DHCPv6.Client.i.Server.i*/
#define RDM_OID_DHCPV6_CLIENT_SENT_OPT           102888	/*Device.DHCPv6.Client.i.SentOption.i*/
#define RDM_OID_DHCPV6_CLIENT_RECEIVED_OPT       103020	/*Device.DHCPv6.Client.i.ReceivedOption.i*/
#define RDM_OID_DHCPV6_SRV                       103128	/*Device.DHCPv6.Server*/
#define RDM_OID_DHCPV6_SRV_POOL                  103212	/*Device.DHCPv6.Server.Pool.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT           103968	/*Device.DHCPv6.Server.Pool.i.Client.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_V6_ADDR   104148	/*Device.DHCPv6.Server.Pool.i.Client.i.IPv6Address.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_V6_PREFIX 104256	/*Device.DHCPv6.Server.Pool.i.Client.i.IPv6Prefix.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_OPT       104364	/*Device.DHCPv6.Server.Pool.i.Client.i.Option.i*/
#define RDM_OID_DHCPV6_SRV_POOL_OPT              104448	/*Device.DHCPv6.Server.Pool.i.Option.i*/
#define RDM_OID_IEEE8021X                        104604	/*Device.IEEE8021x*/
#define RDM_OID_IEEE8021X_SUPPLICANT             104664	/*Device.IEEE8021x.Supplicant.i*/
#define RDM_OID_IEEE8021X_SUPPLICANT_STAT        105132	/*Device.IEEE8021x.Supplicant.i.Stats*/
#define RDM_OID_IEEE8021X_SUPPLICANT_EAPMD5      105432	/*Device.IEEE8021x.Supplicant.i.EAPMD5*/
#define RDM_OID_IEEE8021X_SUPPLICANT_EAPTLS      105516	/*Device.IEEE8021x.Supplicant.i.EAPTLS*/
#define RDM_OID_USRS                             105600	/*Device.Users*/
#define RDM_OID_USRS_USR                         105660	/*Device.Users.User.i*/
#define RDM_OID_SMART_CARD_READERS               105840	/*Device.SmartCardReaders*/
#define RDM_OID_SMART_CARD_READERS_SCR           105900	/*Device.SmartCardReaders.SmartCardReader.i*/
#define RDM_OID_SMART_CARD_READERS_SCR_SC        106128	/*Device.SmartCardReaders.SmartCardReader.i.SmartCard*/
#define RDM_OID_UPNP                             106284	/*Device.UPnP*/
#define RDM_OID_UPNP_DEV                         106320	/*Device.UPnP.Device*/
#define RDM_OID_UPNP_DEV_CAPB                    106644	/*Device.UPnP.Device.Capabilities*/
#define RDM_OID_UPNP_DISC                        106968	/*Device.UPnP.Discovery*/
#define RDM_OID_UPNP_DISC_ROOT_DEV               107076	/*Device.UPnP.Discovery.RootDevice.i*/
#define RDM_OID_UPNP_DISC_DEV                    107280	/*Device.UPnP.Discovery.Device.i*/
#define RDM_OID_UPNP_DISC_SERVICE                107484	/*Device.UPnP.Discovery.Service.i*/
#define RDM_OID_DLNA                             107664	/*Device.DLNA*/
#define RDM_OID_DLNA_CAPB                        107844	/*Device.DLNA.Capabilities*/
#define RDM_OID_SELF_TEST_DIAG                   108072	/*Device.SelfTestDiagnostics*/
#define RDM_OID_FIREWALL                         108156	/*Device.Firewall*/
#define RDM_OID_FIREWALL_LEVEL                   108480	/*Device.Firewall.Level.i*/
#define RDM_OID_FIREWALL_CHAIN                   108732	/*Device.Firewall.Chain.i*/
#define RDM_OID_FIREWALL_CHAIN_RULE              108888	/*Device.Firewall.Chain.i.Rule.i*/
#define RDM_OID_PERD_STATISTICS                  110004	/*Device.PeriodicStatistics*/
#define RDM_OID_PERD_STATISTICS_SAMPLE_SET       110112	/*Device.PeriodicStatistics.SampleSet.i*/
#define RDM_OID_PERD_STATISTICS_SAMPLE_SET_PARAM 110460	/*Device.PeriodicStatistics.SampleSet.i.Parameter.i*/
#define RDM_OID_SW_MODULE                        110760	/*Device.SoftwareModules*/
#define RDM_OID_SW_MODULE_EXEC_ENV               110868	/*Device.SoftwareModules.ExecEnv.i*/
#define RDM_OID_SW_MODULE_DEPLOYMENT_UNIT        111384	/*Device.SoftwareModules.DeploymentUnit.i*/
#define RDM_OID_SW_MODULE_EXEC_UNIT              111756	/*Device.SoftwareModules.ExecutionUnit.i*/
#define RDM_OID_FAULT_MGMT                       112296	/*Device.FaultMgmt*/
#define RDM_OID_FAULT_MGMT_SUPT_ALARM            112476	/*Device.FaultMgmt.SupportedAlarm.i*/
#define RDM_OID_FAULT_MGMT_CURRENT_ALARM         112632	/*Device.FaultMgmt.CurrentAlarm.i*/
#define RDM_OID_FAULT_MGMT_HISTORY_EVENT         112908	/*Device.FaultMgmt.HistoryEvent.i*/
#define RDM_OID_FAULT_MGMT_EXPEDITED_EVENT       113184	/*Device.FaultMgmt.ExpeditedEvent.i*/
#define RDM_OID_FAULT_MGMT_QUED_EVENT            113460	/*Device.FaultMgmt.QueuedEvent.i*/
#define RDM_OID_DEV_SEC                          113736	/*Device.Security*/
#define RDM_OID_DEV_SEC_CERT                     113796	/*Device.Security.Certificate.i*/
#define RDM_OID_FAP                              114264	/*Device.FAP*/
#define RDM_OID_FAP_GPS                          114300	/*Device.FAP.GPS*/
#define RDM_OID_FAP_GPS_CONTS_GPS_STATUS         114672	/*Device.FAP.GPS.ContinuousGPSStatus*/
#define RDM_OID_FAP_GPS_AGPS_SRV_CONF            115044	/*Device.FAP.GPS.AGPSServerConfig*/
#define RDM_OID_FAP_PERF_MGMT                    115272	/*Device.FAP.PerfMgmt*/
#define RDM_OID_FAP_PERF_MGMT_CONF               115332	/*Device.FAP.PerfMgmt.Config.i*/
#define RDM_OID_FAP_APP_PLATF                    115536	/*Device.FAP.ApplicationPlatform*/
#define RDM_OID_FAP_APP_PLATF_CAPB               115692	/*Device.FAP.ApplicationPlatform.Capabilities*/
#define RDM_OID_FAP_APP_PLATF_CTRL               116040	/*Device.FAP.ApplicationPlatform.Control*/
#define RDM_OID_FAP_APP_PLATF_CTRL_FEMTO_AWARE   116124	/*Device.FAP.ApplicationPlatform.Control.FemtoAwareness*/
#define RDM_OID_FAP_APP_PLATF_CTRL_SMS           116352	/*Device.FAP.ApplicationPlatform.Control.SMS*/
#define RDM_OID_FAP_APP_PLATF_CTRL_MMS           116556	/*Device.FAP.ApplicationPlatform.Control.MMS*/
#define RDM_OID_FAP_APP_PLATF_CTRL_TERM_LOC      116760	/*Device.FAP.ApplicationPlatform.Control.TerminalLocation*/
#define RDM_OID_FAP_APP_PLATF_MONT               116988	/*Device.FAP.ApplicationPlatform.Monitoring*/
#define RDM_OID_FAP_APP_PLATF_MONT_FEMTO_AWARE   117120	/*Device.FAP.ApplicationPlatform.Monitoring.FemtoAwareness*/
#define RDM_OID_FAP_APP_PLATF_MONT_SMS           117300	/*Device.FAP.ApplicationPlatform.Monitoring.SMS*/
#define RDM_OID_FAP_APP_PLATF_MONT_MMS           117480	/*Device.FAP.ApplicationPlatform.Monitoring.MMS*/
#define RDM_OID_FAP_APP_PLATF_MONT_TERM_LOC      117660	/*Device.FAP.ApplicationPlatform.Monitoring.TerminalLocation*/
#define RDM_OID_BULK_DATA                        117840	/*Device.BulkData*/
#define RDM_OID_BULK_DATA_PROF                   118068	/*Device.BulkData.Profile.i*/
#define RDM_OID_BULK_DATA_PROF_PARAM             118440	/*Device.BulkData.Profile.i.Parameter.i*/
#define RDM_OID_ROM_CONVERT                      118500	/*Device.X_ZYXEL_RomConvert.i*/
#define RDM_OID_SCHEDULE                         118560	/*Device.X_ZYXEL_Schedule.i*/
#define RDM_OID_EMAIL_NOTIFY                     118860	/*Device.X_ZYXEL_EmailNotification*/
#define RDM_OID_MAIL_SERVICE                     118896	/*Device.X_ZYXEL_EmailNotification.EmailService.i*/
#define RDM_OID_MAIL_EVENT_CFG                   119124	/*Device.X_ZYXEL_EmailNotification.EmailEventConfig.i*/
#define RDM_OID_PAREN_CTL                        119304	/*Device.X_ZYXEL_ParentalControl*/
#define RDM_OID_PAREN_CTL_PROF                   119364	/*Device.X_ZYXEL_ParentalControl.Profile.i*/
#define RDM_OID_IEEE8021AG                       119688	/*Device.X_ZYXEL_8021ag*/
#define RDM_OID_IEEE8023AH                       120180	/*Device.X_ZYXEL_8023ah*/
#define RDM_OID_ZY_EXT                           120432	/*Device.X_ZYXEL_EXT*/
#define RDM_OID_DNS_RT_ENTRY                     120540	/*Device.X_ZYXEL_EXT.DNSRouteEntry.i*/
#define RDM_OID_DNS_ENTRY                        120768	/*Device.X_ZYXEL_EXT.DNSEntry.i*/
#define RDM_OID_D_DNS                            120852	/*Device.X_ZYXEL_EXT.DynamicDNS*/
#define RDM_OID_AUTO_PROV                        121272	/*Device.X_ZYXEL_EXT.AutoProvision*/
#define RDM_OID_SPEED_TEST                       121500	/*Device.X_ZYXEL_EXT.SpeedTestInfo*/
#define RDM_OID_WIFI_QSTEER                      121680	/*Device.X_ZYXEL_EXT.Qsteer*/
#define RDM_OID_ZY_HOST_NAME_REPLACE             121812	/*Device.X_ZYXEL_EXT.HostNameReplace*/
#define RDM_OID_PPTP_CFG                         121872	/*Device.X_ZYXEL_EXT.X_ZYXEL_PPTP_Config*/
#define RDM_OID_EOGRE_CFG                        122172	/*Device.X_ZYXEL_EXT.X_ZYXEL_EoGRE_Config*/
#define RDM_OID_LAN_DEV                          122352	/*Device.X_ZYXEL_EXT.LANDevice.i*/
#define RDM_OID_EASY_MESH                        122460	/*Device.X_ZYXEL_EXT.EasyMesh*/
#define RDM_OID_MAC_ADDRESS_TABLE                122568	/*Device.X_ZYXEL_EXT.MacAddressTable*/
#define RDM_OID_LINK_QUALITY                     122772	/*Device.X_ZYXEL_EXT.LinkQuality*/
#define RDM_OID_ZY_IGMP                          122880	/*Device.X_ZYXEL_IGMP*/
#define RDM_OID_ZY_SNMP                          123372	/*Device.X_ZYXEL_SNMP*/
#define RDM_OID_TRAP_ADDR                        123528	/*Device.X_ZYXEL_SNMP.TrapAddr.i*/
#define RDM_OID_ZY_MLD                           123636	/*Device.X_ZYXEL_MLD*/
#define RDM_OID_ZY_LOG_CFG                       124056	/*Device.X_ZYXEL_LoginCfg*/
#define RDM_OID_ZY_LOG_CFG_GP                    124164	/*Device.X_ZYXEL_LoginCfg.LogGp.i*/
#define RDM_OID_ZY_LOG_CFG_GP_ACCOUNT            124320	/*Device.X_ZYXEL_LoginCfg.LogGp.i.Account.i*/
#define RDM_OID_ZY_MAC_FILTER                    125172	/*Device.X_ZYXEL_MacFilter*/
#define RDM_OID_ZY_MAC_FILTER_WHITE_LIST         125280	/*Device.X_ZYXEL_MacFilter.WhiteList.i*/
#define RDM_OID_WLAN_SCHEDULER_ACCESS            125388	/*Device.X_ZYXEL_WlanSchedulerAccess*/
#define RDM_OID_VC_AUTO_HUNT                     125496	/*Device.X_ZYXEL_VcAutoHunt*/
#define RDM_OID_VC_HUNT_INFO                     125652	/*Device.X_ZYXEL_VcAutoHunt.VcHuntInfo.i*/
#define RDM_OID_VC_HUNT_RULE                     125736	/*Device.X_ZYXEL_VcAutoHunt.VcHuntInfo.i.VcHuntRule.i*/
#define RDM_OID_VLAN_AUTO_HUNT                   125820	/*Device.X_ZYXEL_VlanAutoHunt*/
#define RDM_OID_VLAN_HUNT_INFO                   125952	/*Device.X_ZYXEL_VlanAutoHunt.VlanHuntInfo.i*/
#define RDM_OID_VLAN_HUNT_RULE                   126036	/*Device.X_ZYXEL_VlanAutoHunt.VlanHuntInfo.i.VlanHuntRule.i*/
#define RDM_OID_LANG                             126120	/*Device.X_ZYXEL_Language*/
#define RDM_OID_REMO_MGMT                        126180	/*Device.X_ZYXEL_RemoteManagement*/
#define RDM_OID_REMO_SRV                         126288	/*Device.X_ZYXEL_RemoteManagement.Service.i*/
#define RDM_OID_REMO_SRV_TRUST_DOMAIN            126588	/*Device.X_ZYXEL_RemoteManagement.Service.i.TrustDomain.i*/
#define RDM_OID_SP_REMO_SRV                      126696	/*Device.X_ZYXEL_RemoteManagement.SPService.i*/
#define RDM_OID_SP_REMO_SRV_TRUST_DOMAIN         126996	/*Device.X_ZYXEL_RemoteManagement.SPService.i.TrustDomain.i*/
#define RDM_OID_REMO_MGMT_TRUST_DOMAIN           127128	/*Device.X_ZYXEL_RemoteManagement.TrustDomain.i*/
#define RDM_OID_SP_TRUST_DOMAIN                  127236	/*Device.X_ZYXEL_RemoteManagement.SPTrustDomain.i*/
#define RDM_OID_NETWORK_SRV                      127368	/*Device.X_ZYXEL_NetworkService*/
#define RDM_OID_NETWORK_SRV_GP                   127428	/*Device.X_ZYXEL_NetworkService.Service.i*/
#define RDM_OID_SYSTEM_INFO                      127680	/*Device.X_ZYXEL_System_Info*/
#define RDM_OID_GPON_INFO                        127956	/*Device.X_ZYXEL_GPON_Info*/
#define RDM_OID_LOG_SETTING                      128160	/*Device.X_ZYXEL_Log_Setting*/
#define RDM_OID_LOG_CLASSIFY                     128364	/*Device.X_ZYXEL_Log_Setting.LogClassify.i*/
#define RDM_OID_LOG_CATEGORY                     128472	/*Device.X_ZYXEL_Log_Setting.LogClassify.i.Category.i*/
#define RDM_OID_CHANGE_ICON_NAME                 128652	/*Device.X_ZYXEL_Change_Icon_Name.i*/
#define RDM_OID_PORT_MIRROR                      129000	/*Device.X_ZYXEL_PortMirroring.i*/
#define RDM_OID_VLAN_GROUP                       129132	/*Device.X_ZYXEL_VlanGroup.i*/
#define RDM_OID_S_T_B_VENDOR_I_D                 129312	/*Device.X_ZYXEL_STB_VENDOR_ID*/
#define RDM_OID_T_F_T_P_SRV_NAME                 129468	/*Device.X_ZYXEL_TFTP_SERVER_NAME*/
#define RDM_OID_TR064                            129528	/*Device.X_ZYXEL_TR064*/
#define RDM_OID_ACL                              129708	/*Device.X_ZYXEL_TR064.ACL*/
#define RDM_OID_CONTROL_POINT                    129744	/*Device.X_ZYXEL_TR064.ACL.CP.i*/
#define RDM_OID_ACTIONS                          129876	/*Device.X_ZYXEL_TR064.ACL.Actions.i*/
#define RDM_OID_ZY_W_W_A_N_BACKUP                129984	/*Device.X_ZYXEL_WWAN_BACKUP*/
#define RDM_OID_ZY_BAND_WIDTH_IMPROVEMENT        130452	/*Device.X_ZYXEL_WWAN_BACKUP.BandWidthImprovement*/
#define RDM_OID_ZY_W_W_A_N_PING_CHECK            130608	/*Device.X_ZYXEL_WWAN_BACKUP.PingCheck*/
#define RDM_OID_ZY_W_W_A_N_BUDGET_CONTROL        130764	/*Device.X_ZYXEL_WWAN_BACKUP.BudgetControl*/
#define RDM_OID_ZY_W_W_A_N_STAT                  131448	/*Device.X_ZYXEL_WWAN_BACKUP.Stats*/
#define RDM_OID_ZY_SAMBA                         131700	/*Device.X_ZYXEL_SAMBA*/
#define RDM_OID_ZY_SAMBA_DIR                     131808	/*Device.X_ZYXEL_SAMBA.Directory.i*/
#define RDM_OID_GUI_CUSTOMIZATION                132060	/*Device.X_ZYXEL_GUI_CUSTOMIZATION*/
#define RDM_OID_INPUT_CHECK_LIST                 132528	/*Device.X_ZYXEL_GUI_CUSTOMIZATION.InputCheckList.i*/
#define RDM_OID_FEATURE_FLAG                     132708	/*Device.X_ZYXEL_FEATRUE_FLAG*/
#define RDM_OID_ZY_OPTION125                     133224	/*Device.X_ZYXEL_Option125VendorSpecific*/
#define RDM_OID_ZY_VENDOR_SPECIFIC               133284	/*Device.X_ZYXEL_Option125VendorSpecific.VendorSpecific.i*/
#define RDM_OID_ZY_IPP_CFG                       133416	/*Device.X_ZYXEL_Ipp_Cfg*/
#define RDM_OID_GPON                             133548	/*Device.X_ZYXEL_GPON*/
#define RDM_OID_ONU                              133584	/*Device.X_ZYXEL_GPON.ONU*/
#define RDM_OID_ANI                              134292	/*Device.X_ZYXEL_GPON.ANI*/
#define RDM_OID_OLT                              134760	/*Device.X_ZYXEL_GPON.OLT*/
#define RDM_OID_CAPABILITY                       134892	/*Device.X_ZYXEL_GPON.Capability*/
#define RDM_OID_LOIDAUTH                         135000	/*Device.X_ZYXEL_GPON.LOIDAuth*/
#define RDM_OID_SOFTIMAGE                        135108	/*Device.X_ZYXEL_GPON.SoftImage.i*/
#define RDM_OID_PM                               135240	/*Device.X_ZYXEL_GPON.PM*/
#define RDM_OID_COMMON                           135396	/*Device.X_ZYXEL_GPON.Common*/
#define RDM_OID_XPON                             135480	/*Device.X_ZYXEL_GPON.Xpon*/
#define RDM_OID_LINKCFG                          135636	/*Device.X_ZYXEL_GPON.LinkCfg*/
#define RDM_OID_IPHOST                           135720	/*Device.X_ZYXEL_GPON.IPHost*/
#define RDM_OID_OMCI_CFG                         135804	/*Device.X_ZYXEL_GPON.OmciConfig*/
#define RDM_OID_OMCI                             135840	/*Device.X_ZYXEL_GPON.OmciConfig.Omci*/
#define RDM_OID_GEMPORT                          136044	/*Device.X_ZYXEL_GPON.OmciConfig.GEMPort*/
#define RDM_OID_TCONT                            136200	/*Device.X_ZYXEL_GPON.OmciConfig.TCONT*/
#define RDM_OID_TRTCM                            136284	/*Device.X_ZYXEL_GPON.OmciConfig.Trtcm*/
#define RDM_OID_QOSCFG                           136440	/*Device.X_ZYXEL_GPON.OmciConfig.QosCfg*/
#define RDM_OID_QOS_VALUE                        136620	/*Device.X_ZYXEL_GPON.OmciConfig.QosCfg.QOSValue.i*/
#define RDM_OID_CNGSTCFG                         136680	/*Device.X_ZYXEL_GPON.OmciConfig.CngstCfg*/
#define RDM_OID_CONGEST_THRED_VALUE              136908	/*Device.X_ZYXEL_GPON.OmciConfig.CngstCfg.CongestThredValue.i*/
#define RDM_OID_TRTCMCFG                         136968	/*Device.X_ZYXEL_GPON.OmciConfig.TrtcmCfg*/
#define RDM_OID_TRTCM_VALUE                      137100	/*Device.X_ZYXEL_GPON.OmciConfig.TrtcmCfg.TrtcmValue.i*/
#define RDM_OID_QUEUE                            137160	/*Device.X_ZYXEL_GPON.OmciConfig.Queue*/
#define RDM_OID_ONT_GENERIC                      137220	/*Device.X_ZYXEL_GPON.OntGeneric*/
#define RDM_OID_ZY_ONE_CONNECT                   137280	/*Device.X_ZYXEL_OneConnect*/
#define RDM_OID_ONE_CONNECT_INTERNET_ACCESS_MASTER_SWITCH 137484	/*Device.X_ZYXEL_OneConnect_Internet_Access_Filter*/
#define RDM_OID_ONE_CONNECT_INTERNET_ACCESS_RULE 137568	/*Device.X_ZYXEL_OneConnect_Internet_Access_Filter.Rule.i*/
#define RDM_OID_ONE_CONNECT_P_C_GENERAL          137700	/*Device.X_ZYXEL_OneConnect_Parental_Control*/
#define RDM_OID_ONE_CONNECT_P_C_RULE             137808	/*Device.X_ZYXEL_OneConnect_Parental_Control.Rule.i*/
#define RDM_OID_ONLINE_F_W_UPGRADE               138084	/*Device.X_ZYXEL_Online_FW_Upgrade*/
#define RDM_OID_LANDING_PAGE                     138336	/*Device.X_ZYXEL_Landing_Page*/
#define RDM_OID_POWER_MGMT                       138420	/*Device.X_ZYXEL_Power_Management*/
#define RDM_OID_POWER_SCHEDULE                   138816	/*Device.X_ZYXEL_Power_Management.PowerSchedule.i*/
#define RDM_OID_ZY_LOOP_GUARD                    138972	/*Device.X_ZYXEL_LOOP_GUARD*/
#define RDM_OID_ZY_PROXIMITY_SENSOR              139080	/*Device.X_ZYXEL_PROXIMITY_SENSOR*/
#define RDM_OID_ZY_SFP_MANAGEMENT                139140	/*Device.X_ZYXEL_SFP_Management*/
#define RDM_OID_ZY_RESET_ADMIN                   139224	/*Device.X_ZYXEL_RESET_ADMIN*/
#define RDM_OID_OI_WIZARD                        139284	/*Device.X_ZYXEL_OiWizard*/
#define RDM_OID_ZY_DATA_USAGE                    139488	/*Device.X_ZYXEL_DataUsage*/
#define RDM_OID_ZY_DATA_USAGE_LAN                139548	/*Device.X_ZYXEL_DataUsage.Lan.i*/
#define RDM_OID_ZY_DATA_USAGE_WAN                139656	/*Device.X_ZYXEL_DataUsage.Wan.i*/
#define RDM_OID_IPERF                            139764	/*Device.X_TELECOMITALIA_IT_Iperf*/
#define RDM_OID_ZLOG_CONFIG                      139896	/*Device.X_ZYXEL_Zlog_Setting*/
#define RDM_OID_ZLOG_CATEGORY                    139980	/*Device.X_ZYXEL_Zlog_Setting.ZlogCategory.i*/
#define RDM_OID_HOME_CYBER_SECURITY              140328	/*Device.X_ZYXEL_HomeCyberSecurity*/
#define RDM_OID_CONTENT_FILTER                   140484	/*Device.X_ZYXEL_ContentFilter.i*/
#define RDM_OID_U_R_L_FILTER                     140976	/*Device.X_ZYXEL_URLFilter.i*/
#define RDM_OID_WHITE_U_R_L_FILTER               141108	/*Device.X_ZYXEL_URLFilter.i.WhiteList.i*/
#define RDM_OID_BLACK_U_R_L_FILTER               141216	/*Device.X_ZYXEL_URLFilter.i.BlackList.i*/
#define RDM_OID_ZY_LICNSE                        141324	/*Device.X_ZYXEL_License*/
#define RDM_OID_MOS                              141384	/*Device.X_ZYXEL_Mos*/
#define RDM_OID_MOS_USR_CFG                      141420	/*Device.X_ZYXEL_Mos.MosUserConfig*/
#define RDM_OID_OMCI_VLAN_INFO                   143136	/*Device.X_ZYXEL_Mos.OmciVlanInfo.i*/
#define RDM_OID_XMPP                             143412	/*Device.XMPP*/
#define RDM_OID_XMPP_CONN                        143472	/*Device.XMPP.Connection.i*/
#define RDM_OID_XMPP_CONN_SRV                    143820	/*Device.XMPP.Connection.i.Server.i*/
#define RDM_OID_SYSTEM_DEBUG                     144000	/*Device.X_ZYXEL_System_Debug*/

#define RDM_OID_MAX                   144156     // for OID validation

#define RDM_OID_IS_INVALID(_oid_)    ((_oid_ < 0) || (_oid_ >= RDM_OID_MAX))

#endif // _ZCFG_RDM_OID_H
